### ISSUE TITLE
Every Fedora Labs links wrong

### ISSUE THREAD

**Issue by SzekiTom** [MartinBriza/MediaWriter#101]
e.g. Astronomy:
![kepernyokep 2017-07-22 08-12-13](https://user-images.githubusercontent.com/30338197/28488916-befd10a8-6eb5-11e7-9ba6-fcd12fbaf5f9.png)

But the right link is https://download.fedoraproject.org/pub/alt/releases/26/Labs/x86_64/iso/Fedora-Astronomy_KDE-Live-x86_64-26-1.5.iso

**Comment by MartinBriza** [comment]
Oh no, the metadata is wrong. I'll report it to the websites team.

**Comment by MartinBriza** [comment]
https://pagure.io/fedora-websites/issue/705

**Comment by SzekiTom** [comment]
Tnx!
