### ISSUE TITLE
Keyboard navigation - needs to be improoved / implemented.

### ISSUE THREAD

**Issue by pawiecki** [MartinBriza/MediaWriter#102]
Hi. I like this app, but I can't use it with keyboard only. Maybe there are shortcuts, but I can't find them.

Please make it a keyboard friendly app :)

**Comment by MartinBriza** [comment]
I can't say anything but "yes". I definitely need to implement this.

**Comment by 07416** [comment]
The keyboard navigation may not work, I can't use the app at all without mouse.

version 5.0.6  
Fedora 38 on Gnome
