### ISSUE TITLE
Reset USB Stick dialogue is unclear

### ISSUE THREAD

**Issue by ramirocantu** [MartinBriza/MediaWriter#103]
`"Your computer will now report this drive is much smaller than it really is. Just insert your drive again while Fedora Media Writer is running and you'll be able to restore it back to its full size."` 
This appears while the drive is being written to. It is difficult to understand what this means. Should I unplug my usb and replug it, now? While it's writing? Should I wait until it finishes? 

And finally: "Your computer will now report this drive ~~is~~ as much smaller than it really is."

**Comment by MartinBriza** [comment]
You're right this is confusing. It's hard to really describe what happens in a few words. I'll reword this message for the next version based on your suggestion, thank you!

**Comment by MartinBriza** [comment]
What would you think about this?
`"Your computer will now most likely report this drive as much smaller than it really is. To fix that after trying or installing Fedora, insert your drive again while Fedora Media Writer is running. You will be able to restore it back to its full size."`

**Comment by ramirocantu** [comment]
> "Your computer will now most likely report this drive as much smaller than it really is. To fix that after trying or installing Fedora, insert your drive again while Fedora Media Writer is running. You will be able to restore it back to its full size."

"Your drive will be reformatted to a smaller capacity. You may resize it back to normal by using the Fedora Media Writer; this will remove installation media from your drive."
