### ISSUE TITLE
Using GNOME, but MediaWriter 4.1.0 requires KDE runtime

### ISSUE THREAD

**Issue by chemelnucfin** [MartinBriza/MediaWriter#105]
Trying to get back my desktop Fedora with a Ubuntu 16.04 laptop.  Not sure if it's I don't know how to use flatpak or if I don't know how to use MediaWriter.
Thanks.

$ flatpak install org.fedoraproject.MediaWriter-4.1.0.flatpak
Required runtime for org.fedoraproject.MediaWriter/x86_64/master (org.kde.Platform/x86_64/master) is not installed, searching...
The required runtime org.kde.Platform/x86_64/master was not found in a configured remote.
error: The Application org.fedoraproject.MediaWriter/x86_64/master requires the runtime org.kde.Platform/x86_64/master which is not installed

$ flatpak remote-list
Name  Options
gnome system

**Comment by MartinBriza** [comment]
Yes, this is not a bug but completely intended and unavoidable. Fedora Media Writer is written using the Qt framework, which is what the KDE projects are based on. The GNOME runtime doesn't provide it, hence FMW has to get the Qt dependency from somewhere. The KDE framework is maintained and actively developed so it's a good choice to get the dependency from there.

**Comment by chemelnucfin** [comment]
I tried installing the flatpak for kde platform, but it still seems to mismatch the master and 5.9 branches.  Is there a way for me to fix this in gnome?  The error message is still the same as in the first comment.
Thanks.

$ flatpak list
Ref                            Options       
org.gnome.Platform/x86_64/3.24 system,runtime
org.kde.Platform/x86_64/5.9    system,runtime
org.kde.Sdk/x86_64/5.9         system,runtime
