### ISSUE TITLE
Where are the ISO files saved?

### ISSUE THREAD

**Issue by rugk** [MartinBriza/MediaWriter#107]
Especially when having problems with XP (https://github.com/MartinBriza/MediaWriter/issues/52) e.g., one may download the ISOs and then experience problems when trying to burn them using this application.

So it would be nice to know where the ISO files are saved, so one can just grab them and continue the burning task with another application.

**Comment by squimrel** [comment]
In [the folder Qt specifies as the download folder](https://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum). On Windows that seems to be the Documents folder.

**Comment by MartinBriza** [comment]
Not sure about Windows XP but it's saved wherever Qt decides is the right folder. On newer Windows versions, it's your Downloads folder. But as I said, I'm not sure if that existed on Windows XP... If you really need the info, I'll look it up for you, just let me know.
