### ISSUE TITLE
Not creating live USB

### ISSUE THREAD

**Issue by mohanboddu** [MartinBriza/MediaWriter#11]
I faced following issues with creating the live USB:

The following issues occured before it started actually downloading the image

1. Error creating SSL Context()
2. Error transferring http://linux.mirrors.es.net/fedora/releases/24/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-24-1.2.iso - server replied: Requested Range Not Satisfiable
3. Unknown protocol specified

After couple of retries it started downloading the Fedora 24 64 bit image but after downloading the following message popped:

1. The downloaded image is corrupted.

I am using Windows 10 64 bit.

**Comment by puiterwijk** [comment]
The Windows version's checksum validation is broken: the downloaded file has a correct checksum (validated manually), but the media writer tells me that the image is corrupted. Win 10 x86_64 too.

**Comment by MartinBriza** [comment]
The cheksum validation code should be fixed now. Please verify if you still suffer from the download problems you mentioned first. I'll push a new release (3.96.0) later today for you to test.

**Comment by MartinBriza** [comment]
I think all of the issues mentioned in this issue are fixed now by multiple commits. If you think otherwise, you're welcome to reopen the bug with more details!
