### ISSUE TITLE
org.kde.Platform//5.9 and org.kde.Platform//master mismatch

### ISSUE THREAD

**Issue by chemelnucfin** [MartinBriza/MediaWriter#112]
I tried installing the flatpak for kde platform, but it still seems to mismatch the master and 5.9 branches. Is there a way for me to fix this in gnome? 
This is a standalone issue, but can also refer to#105.
Thanks.

$ flatpak list
Ref Options
org.gnome.Platform/x86_64/3.24 system,runtime
org.kde.Platform/x86_64/5.9 system,runtime
org.kde.Sdk/x86_64/5.9 system,runtime

$ flatpak install org.fedoraproject.MediaWriter-4.1.0.flatpak
Required runtime for org.fedoraproject.MediaWriter/x86_64/master (org.kde.Platform/x86_64/master) is not installed, searching...
The required runtime org.kde.Platform/x86_64/master was not found in a configured remote.
error: The Application org.fedoraproject.MediaWriter/x86_64/master requires the runtime org.kde.Platform/x86_64/master which is not installed

**Comment by MartinBriza** [comment]
Hmmm, it seems KDE started to version their runtimes. The next FMW release (in a few days or weeks) will be compiled using 5.9.

**Comment by chriselrod** [comment]
Any updates?

**Comment by MartinBriza** [comment]
This is now fixed with 4.1.1. Also, FMW is now on Flathub.
