### ISSUE TITLE
Crashes after selecting Fedora version or custom ISO, while running on Fedora

### ISSUE THREAD

**Issue by terrycloth** [MartinBriza/MediaWriter#115]
It's funny, I seem to be having the opposite problem of some other people: MediaWriter crashes when running in Fedora, but _not_ on Windows.

I've tried selecting one of the default Fedora versions from the menus, and I've tried manually downloading a Fedora ISO image and selecting that. When running in Fedora, MediaWriter always freezes before I can begin installing the live media to my flash drive. Sometimes just the application itself freezes, and I can kill it and try again or do something else. Often the whole system freezes, though, and after waiting a minute or two, I have to do a "hard" reboot.

I couldn't find any log files, and it's hard to see terminal output when the whole system crashes.

My system setup:

- Fedora 26 Workstation x86_64
- mediawriter 4.1.0-1.fc26
- GNOME 3.24.2 in an Xorg session
- open source graphics driver: xorg-x11-drv-nouveau-1.0.15-1.fc26
- I've also tried on two different machines, both using the same software but with different graphics cards:
    - Nvidia GeForce GTX 560 Ti
    - Nvidia GeForce GTX 650

**Comment by terrycloth** [comment]
Huh. Since which graphics card the user has has been a recurring question in other threds, I thought to try it again after installing the proprietary Nvidia drivers from RPM Fusion. MediaWriter worked perfectly then.

**Comment by MartinBriza** [comment]
Yeah, nouveau + Qt = bad times. 
Anyway, I switched to preferring the software rendering backend yesterday so in 4.1.1 it won't crash for anyone in exchange for some CPU power (not much though).
