### ISSUE TITLE
f24 links for custom and spins D/L are not correct in windows and mac MediaWriter 3.95.0

### ISSUE THREAD

**Issue by satellitee** [MartinBriza/MediaWriter#12]
<satellit> I am not getting a download of custom or kde from windows  only workstation and server seem to have correct links to f24
<satellit> Thinkpad T560
<satellit> https://github.com/MartinBriza/MediaWriter/releases/download/3.95.0/FMW-setup.exe
<mbriza> thanks for the report, i'll take a look at it

Same behaviour in https://github.com/MartinBriza/MediaWriter/releases/download/3.95.0/mediawriter.dmg
also it is unsigned

**Comment by MartinBriza** [comment]
Thanks for reporting. I fixed this already in f932fca4096d13c43a29cf05ce2fe2799f95e82d .

**Comment by MartinBriza** [comment]
I don't possess the Mac signing certificate though. Only official Fedora builds will be signed.
