### ISSUE TITLE
HiDPI awareness on Windows

### ISSUE THREAD

**Issue by hmaarrfk** [MartinBriza/MediaWriter#121]
I don't know if this is a GTK bug, but on an XPS 15 with a 4k screen, and an external 1080p monitor, it behaves very strangely when dragging accross both monitors. Screenshots attached.

On my 4k screen (bottom) I have the scaling set to 200% on windows so that things are legible.

![on4k](https://user-images.githubusercontent.com/90008/30441893-9dddac76-992f-11e7-9dee-6c20b2dc4844.png)
![on1080p](https://user-images.githubusercontent.com/90008/30441894-9e03a642-992f-11e7-86cb-920040ff7019.png)

 

Great work.

**Comment by MartinBriza** [comment]
This is actually a Qt driver bug, I have noticed this too and it's "fixed" already in master (that means I'm resorting to software rendering). High DPI scaling on itself should work just fine, it's built in in Qt.

**Comment by hmaarrfk** [comment]
Great thanks.
