### ISSUE TITLE
mediawriter command no longer opening program

### ISSUE THREAD

**Issue by karl69942** [MartinBriza/MediaWriter#125]
Hello! Long-time MediaWriter user here, I'm having trouble getting it to open up all of a sudden!! I had it working before, but since the update, the icon has disappeared & the command isn't working! Am I going crazy or have you changed the command to open the program up with? :S
I'm running Manjaro Linux(Arch variant) & Debian Linux, mediawriter command still works on Debian, even on the new release, but not on Manjaro.. Weird.
PACAUR tells me that I have mediawriter installed, but I can't make it launch, tells me the command isn't right.. I might try to switch back to the version before 4.1.0.. I made this "issue" on another account but the account got "flagged" so I can't find the "issue" on this account.
this is what I see now:

mediawriter
bash: mediawriter: command not found
[kz@kz ~]$ pacaur -S mediawriter
:: Package mediawriter not found in repositories, trying AUR...
:: resolving dependencies...
:: looking for inter-conflicts...
:: mediawriter-4.1.0-5 is up to date -- reinstalling

AUR Packages (1) mediawriter-4.1.0-5

:: Proceed with installation? [Y/n]

**Comment by karl69942** [comment]
pacaur -S mediawriter
:: Package mediawriter not found in repositories, trying AUR...
:: resolving dependencies...
:: looking for inter-conflicts...

AUR Packages  (1) mediawriter-4.1.0-5  

:: Proceed with installation? [Y/n] n
[kz@kz ~]$ pacaur -R mediawriter
error: target not found: mediawriter
????????? what?????? I can't even remove it? :S this is odd to say the least..

**Comment by MartinBriza** [comment]
To be honest, this looks more like a packaging error than anything I could fix. Please reach out to the point of contact in AUR and ask how to fix your problem.
