### ISSUE TITLE
Crash on macOS Sierra (4.1.0)

### ISSUE THREAD

**Issue by ahmad88me** [MartinBriza/MediaWriter#126]
I'm referring to the app I downloaded from fedora website. But when I clone the code and run it with qt locally on the same mac it works.

**Comment by MartinBriza** [comment]
Please provide more info on what hardware this is and the specific macOS version. Also if you can provide the diagnostic info from the crash dialog, that'd be perfect.

**Comment by max-simon** [comment]
Had exactly the same problem, solved by deactivating Automatic Proxy Detection. See #123 for details 👍

**Comment by MartinBriza** [comment]
Alright, found the problem. It was a Qt bug. Updating Qt and rebuilding FMW fixed it for me. I have updated the build in Releases on Github so you can try it - the filename is FedoraMediaWriter-osx-4.1.1-rebuilt.dmg.
