### ISSUE TITLE
[imp feature request]Sort the attached usb drives in increasing order of size in dropdown menu

### ISSUE THREAD

**Issue by devilex94** [MartinBriza/MediaWriter#128]
Okay so I had my 2TB external drive and my 32GB PD attached on system. And I was in swift mood to create a bootable usb stick. fedora media writer after selecting the ISO by default selected my 2TB HDD instead of my PD.  So yeah my external HDD got f-ed up. I recovered most of my data but still I think if dropdown menu is sorted on basis of drive size then such accidents can be prevented

**Comment by MartinBriza** [comment]
I'm sorry this happened. :( However, your suggestion to sort the drives by
their size is great! I'll implement that for the next version, it'll
definitely help with this problem.

2017-10-14 11:04 GMT+02:00 devilex94 <notifications@github.com>:

**Comment by devilex94** [comment]
Don't worry it's not your fault :) I recovered almost all the data. And I'm glad I could contribute to the project in some way
