### ISSUE TITLE
Crash Windows 10 v1709

### ISSUE THREAD

**Issue by Alkaris** [MartinBriza/MediaWriter#129]
Not sure what to make of this error, but when I start it up, it immediately crashes with a Runtime Error.

![crashywin10](https://user-images.githubusercontent.com/6682988/31863533-3489b3d4-b796-11e7-9e75-d35b829b8664.PNG)

No link to the particular error causing the issue, just crashes with that message and then the program terminates from there. I only downloaded the precompiled binary for Windows, which I downloaded from the official Redhat site that linked to GitHub page here as well as a direct download for the Windows binary executable.

**Comment by MartinBriza** [comment]
liveusb-creator is a different project than this. Where have you downloaded it? Please provide the link.
To use MediaWriter (this project), go either to getfedora.org to get the builds done by the Fedora Release Engineering team, or visit the Releases page inside this GitHub project, there are the builds done by me. It's of course safe to use either.
I'm closing this issue, however please feel free to contact me again in whatever way seems the best, even in the comments below.
