### ISSUE TITLE
Warn with problematic platforms

### ISSUE THREAD

**Issue by rugk** [MartinBriza/MediaWriter#130]
In https://github.com/MartinBriza/MediaWriter/issues/90 I saw that the nouveau driver can cause problems. As the linked issue, however, shows, that this is a horrible UX (especially as you do not notice the issue when opening the app the first time, but only when you actually want to use it) and many bug reports are filled, I suggest to at least show a **warning** when such a platform is detected.

This way users are aware that problems could happen, and won't be surprised if it does not work and fails.

**Comment by MartinBriza** [comment]
I'm actually just switching to software rendering to avoid this kind of issues. It doesn't seem to be overly hardware-demanding to render FMW using the CPU and it fixes crashes on Windows and Linux for quite a lot of people. Wait for 4.1.1.

**Comment by rugk** [comment]
Great news, that you can fix it… 😃
