### ISSUE TITLE
Problems on Arch variant

### ISSUE THREAD

**Issue by kenny-wettlaufer** [MartinBriza/MediaWriter#131]
W@149ms: QGLXContext: Failed to create dummy context
F@327ms: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) 

MediaWriter wasn't opening for me earlier, so I typed in the command & this is what came up. Mediawriter blinks open then closed very fast. Not sure what is wrong... I'm running Artix Linux, the OpenRC Arch variant.

**Comment by MartinBriza** [comment]
Does it run for you with env QMLSCENE_DEVICE=softwarecontext ?

2017-11-02 16:25 GMT+01:00 kenny-wettlaufer <notifications@github.com>:

**Comment by kenny-wettlaufer** [comment]
Hmmm, that seemed to make it work. I tried reopening it again & it worked.

**Comment by MartinBriza** [comment]
Right. That's most likely a graphics driver problem. I'm going to force
software rendering for the next release.

2017-11-03 4:38 GMT+01:00 kenny-wettlaufer <notifications@github.com>:
