### ISSUE TITLE
Application fails to start on Windows 10

### ISSUE THREAD

**Issue by namronb** [MartinBriza/MediaWriter#132]
I'm trying to make a bootable USB stick for Fedora 26 on WIndows 10 Pro (1703, build 15063.674)  getfedora.org provides the link https://getfedora.org/fmw/FedoraMediaWriter-win32-4.1.0.exe .  The software installs OK, but when I try to run it (from the icon or the command prompt), a window briefly opens and then closes.  There is no error dialog, no entry in the windows Application Logs, and nothing printed at the command line.
![fedora_fail](https://user-images.githubusercontent.com/5638051/32549585-4277aa56-c447-11e7-936a-96ad758e563f.png)

**Comment by romkus** [comment]
Looks like I have the same behavior on Windows 7 x64. Here is zip file with execution events saved via Sysinternals process monitor.
[FedoraMediaWriter-win32-4.1.0_02_logFiltered.zip](https://github.com/MartinBriza/MediaWriter/files/1457818/FedoraMediaWriter-win32-4.1.0_02_logFiltered.zip)

**Comment by MartinBriza** [comment]
Can you please try running this: https://mbriza.fedorapeople.org/FedoraMediaWriter-win32-4.1.0-49-gc033629.exe ? It should use the software renderer.

**Comment by namronb** [comment]
That version works great; thanks!  The computer with the problem had Intel
graphics (HD4400).  Another computer with the same version of Windows 10
had NVIDIA graphics and no problem.

**Comment by romkus** [comment]
Yes, it works for me too!.. I have Intel i3-3220 CPU and AMD Radeon HD 8490 on Gigabyte GA-B75M-D2V motherboard.

**Comment by MartinBriza** [comment]
Yay! Thanks for testing the newer build!
I have released 4.1.1 a bunch of days ago, which is now in the Releases section here on Github and it should get to getfedora.org in a few days, too, if you want a "stable" version. :)
