### ISSUE TITLE
The application freezes the computer

### ISSUE THREAD

**Issue by guibos** [MartinBriza/MediaWriter#133]
Fedora 25/26 Xorg

**Comment by MartinBriza** [comment]
Let me guess, you're on the Nouveau driver. 
Please try updating to mediawriter-4.1.1-1.fc26 or mediawriter-4.1.1-1.fc25 from the updates-testing repository. It should fix the problem for you. Please let me know (using this issue or karma on bodhi.fedoraproject.org if you have a FAS account) if it helps. Thank you.
