### ISSUE TITLE
Version information is not displayed in add/remove programs (windows)

### ISSUE THREAD

**Issue by paravz** [MartinBriza/MediaWriter#134]
This is v4.1.1 (fedora 27 release announcement) on Windows7.
$VERSIONMAJOR and such are displayed in add/remove programs:

![image](https://user-images.githubusercontent.com/4796390/32907399-bd6027f2-cab4-11e7-925f-0e2fb8af69b0.png)

**Comment by MartinBriza** [comment]
Oh no, I thought I've fixed that. /o\ I'm sorry about that. Let me fix that for the next release.

**Comment by paravz** [comment]
@MartinBriza thanks! and let me know if you need to test it. And thanks for the great software, got me a new (shiny?) Fedora :)
