### ISSUE TITLE
Latest binary not available on getfedora.org yet

### ISSUE THREAD

**Issue by jmfgdev** [MartinBriza/MediaWriter#135]
If I go to getfedora.org seeking to install the Windows media writer tool, I find that I download the fedora 26 version, as it says in the verison information. I clicked the github link, and found that the current version is 4.1.1, could you get in contact with someone who can get the updated link on the website?

**Comment by MartinBriza** [comment]
Hi, you're right. This is a thing I don't have 100% under control - Fedora Release Engineering does the official getfedora.org releases. You can track the progress here: https://pagure.io/releng/issue/7163 .
I have pinged them on IRC so hopefully things will move forward a bit faster.
