### ISSUE TITLE
Security issue with unsigned uninstall binary that requires UAC

### ISSUE THREAD

**Issue by jmfgdev** [MartinBriza/MediaWriter#136]
Generally users should be accustomed to refusing UAC prompts that are not signed by a verified publisher.
As a security improvement, I would suggest signing the uninstaller in the next release.
That way, users never have to allow any unsigned UAC prompts.

**Comment by MartinBriza** [comment]
You're right. It didn't occur to me the installer is there too as it's
generated by NSIS. I'll have to intercept the installer generation and sign
that binary too, thanks for noticing!

**Comment by jmfgdev** [comment]
You're welcome, thanks for providing the software.
