### ISSUE TITLE
Broken grammar in PRIVACY.md

### ISSUE THREAD

**Issue by jmfgdev** [MartinBriza/MediaWriter#137]
This documentation has issues with a few missing words to connect the sentence together:

```
Fedora Media Writer uses a custom User-Agent header for the Fedora project to have a clear statistic of how prevalent download method it is. 
```

Adjust it to whatever you meant to say, I guess.
I assume you meant to write "...how prevalent of a download..."

**Comment by MartinBriza** [comment]
Yeah, my English is not as good as it could be and you're right about the intended meaning. :) 
If you want to be a part of the commit history, please open a pull request with this change against the master branch. 
Thank you!
