### ISSUE TITLE
While looking for use of http:// instead of https:// I located this broken url

### ISSUE THREAD

**Issue by jmfgdev** [MartinBriza/MediaWriter#139]
http://zanata.org/namespace/config/

seems to be dead, I was going to see if it's available over https instead but the file is not available even over http://

**Comment by MartinBriza** [comment]
Hmm, those files are just used by Zanata and it works fine, I updated the translations last week without a problem. Also the Zanata docs list this URL so there's probably just a problem with their hosting or they changed it and forgot to update everything.
As long as there's no problem with the translations, I'm not going to change anything there.
