### ISSUE TITLE
Dead link / Typo?

### ISSUE THREAD

**Issue by jmfgdev** [MartinBriza/MediaWriter#140]
http://timestamp.verisign.com/scripts/timstamp.dll

to me, this looks like it should be timestamp.dll, but when I go to that url, I find no data as well.
Is there another place this file can be sourced from?

**Comment by MartinBriza** [comment]
This URL is fine, however, this bug made me search for where is this coming from and it seems I should actually be using a different URL: http://sha256timestamp.ws.symantec.com/sha256/timestamp . The binaries I get from that command are fine though so I'll probably not push changing anything in that regard.
See https://knowledge.symantec.com/support/code-signing-support/index?page=content&id=SO15544 if you're interested in this topic.

**Comment by jmfgdev** [comment]
I don't think we should trust http:// delivered anything signature in this program, is it possible to use https instead?

**Comment by MartinBriza** [comment]
I don't know the technical details but as far as I know, this is just use to deliver a timestamp of when the binary was signed. The actual signing happens on the build machine and no third party can intercept it harmfully.

Also, there's nothing I can do about it. The timestamping servers are not hosted over HTTPS.
