### ISSUE TITLE
Drive already "contains a live system", what will restoring to factory settings do?

### ISSUE THREAD

**Issue by jmfgdev** [MartinBriza/MediaWriter#141]
As far as I know, the drive is void of data, but the tool says that it already contains a live system, and offers to restore it to factory settings. @MartinBriza any idea why an empty drive causes this warning?

**Comment by MartinBriza** [comment]
What platform is this? What does "void of data" mean? No partitions? No partition table?
Basically, everywhere except on Linux, it just guesses based on the size of the first detectable partition. For example Windows provides virtually no information about the filesystem of partitions.

**Comment by jmfgdev** [comment]
By void of data I mean no partitions, unallocated.
This was on Windows, so yeah it's just an issue of accuracy.

**Comment by scootergrisen** [comment]
Its seems incorrect to me that the software is telling me that the memory card contains a live system when it does not. Like after formatting.

I would prefer it say nothing then say something incorrect.

On Window 7 using FedoraMediaWriter-win32-4.1.4.exe
