### ISSUE TITLE
[flatpak build] Nothing happens when I click "custom image"

### ISSUE THREAD

**Issue by glaubersm** [MartinBriza/MediaWriter#144]
Title says by itself. Mediawriter installed on Arch Linux running Gnome 3.26.2..

**Comment by st346** [comment]
I have the same problem. Installed on Fedora 26 64bit with Gnome. Attempting to make a 32bit live thumb drive but when I select the custom image the dialog goes dead and then the program crashes

**Comment by julianrichen** [comment]
I have the same problem as well.

Output of `flatpak run org.fedoraproject.MediaWriter -v` and contents of `$HOME/Documents/FedoraMediaWriter.log` don't have any related errors to the problem.

**Comment by MartinBriza** [comment]
This is most likely a Platform problem - also, it works for me now in Fedora 27 Workstation with org.kde.Platform installed about 2 weeks ago. Please try updating your KDE Flatpak runtime using this command: `flatpak update org.kde.Platform`.

**Comment by glaubersm** [comment]
the problem is fixed on my Arch Linux.
