### ISSUE TITLE
windows 10 - 3.96.0-(spins); downloads finish but have corrupted message at end

### ISSUE THREAD

**Issue by satellitee** [MartinBriza/MediaWriter#15]
https://github.com/MartinBriza/MediaWriter/releases/download/3.96.0/FedoraMediaWriter.exe

**Comment by MartinBriza** [comment]
What spin/version/variant were you downloading?

**Comment by satellitee** [comment]
soas f24  I tried boot after write to disk and it boots fine in efi on Thinkpad. t560
does it do a checking of image which fails here?
error message can be ignored it seems

**Comment by satellitee** [comment]
MAC testing seems unable to finish spin D/L  halts at 1.1GB remaining ?  (latest 3.96.0)
KDE and cinnamon

**Comment by satellitee** [comment]
What spin/version/variant were you downloading?

soas f24 I tried boot after write to disk and it boots fine in efi on 
Thinkpad. t560
does it do a checking of image which fails here?
error message can be ignored it seems


MAC testing seems unable to finish spin D/L halts at 1.1GB remaining ? 
(latest 3.96.0)
KDE and cinnamon

**Comment by MartinBriza** [comment]
On a Mac, I tried downloading SoaS F24 both 32b and 64b versions as well as KDE and Cinnamon and it worked well except for one interrupted download that could be restarted by reopening the download dialog. Media check went through too.

**Comment by satellitee** [comment]
I just downloaded [1] https://ausil.fedorapeople.org/FMW-setup.exe to my 
windows 10 T560

It does not download any of the spins. or workstation or server "The 
Download image is Corrupted"

[1] https://fedorahosted.org/fedora-qa/ticket/490#comment:5

Is it possible that the repo used is inconsistent?

I note that this is FMW-setup not your 
https://github.com/MartinBriza/MediaWriter/releases/download/3.96.0/FedoraMediaWriter.exe. 
which worked for me yesterday

Is the link on the stg an older version?

Tom Gilliard
satellit

**Comment by MartinBriza** [comment]
I'd probably rely on reporting against what is on Github for now. We'll have to include version numbers in the installers from the fedora websites.

**Comment by satellitee** [comment]
A suggestion; can we use wget to do the .iso downloads in mediawriter? 
(Windows and MAC ;To fix poor downloading performance.)? so downloads 
will continue automatically after an interruption.

Regards;

Tom Gilliard
