### ISSUE TITLE
error: GPG verification enabled, but no signatures found

### ISSUE THREAD

**Issue by mhsabbagh** [MartinBriza/MediaWriter#154]
When trying to install the Flatpak file on Ubuntu 17.10, I get the following error:

```
mhsabbagh@pc:~$ sudo flatpak install '/home/mhsabbagh/Downloads/org.fedoraproject.MediaWriter(1).flatpak'
Updating: org.kde.Platform/x86_64/5.9 from flathub
No updates.
Updating: org.freedesktop.Platform.ffmpeg/x86_64/1.6 from flathub
No updates.
Updating: org.kde.Platform.Locale/x86_64/5.9 from flathub
No updates.
Installing: org.fedoraproject.MediaWriter/x86_64/master from bundle org.fedoraproject.MediaWriter(1).flatpak
error: GPG verification enabled, but no signatures found (use gpg-verify=false in remote config to disable
```

Not sure if it's related to my local system or the package?

**Comment by MartinBriza** [comment]
Does using `flatpak install --from https://flathub.org/repo/appstream/org.fedoraproject.MediaWriter.flatpakref` change anything for you?

**Comment by mhsabbagh** [comment]
Yep! After installing it, I was able to run it via: 

    sudo flatpak run org.fedoraproject.MediaWriter/x86_64/stable

Thanks.

**Comment by MartinBriza** [comment]
Alrighty! So I assume everything is fine and I'll close this. But if you encounter any other issue, please go ahead and create a new one.
