### ISSUE TITLE
Compile problem on Fedora 24 for 3.96.1

### ISSUE THREAD

**Issue by thunderbirdtr** [MartinBriza/MediaWriter#16]
I had to change only "cs.qm" to "cs.po" file in source files then it found the file and complete compile process. 

Thank you* 

Error part*
/////
RCC: Error in '../translations/translations.qrc': Cannot find file 'cs.po'
//// 

//// Full compile list*

cd lib/ && ( test -e Makefile || /usr/bin/qmake-qt5 /home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/lib/lib.pro PREFIX=/usr -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/lib'
cd isomd5/ && ( test -e Makefile || /usr/bin/qmake-qt5 /home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/lib/isomd5/isomd5.pro PREFIX=/usr -o Makefile ) && make -f Makefile 
make[2]: Entering directory '/home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/lib/isomd5'
gcc -c -pipe -O2 -fPIC -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o libcheckisomd5.o libcheckisomd5.c
gcc -c -pipe -O2 -fPIC -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o md5.o md5.c
rm -f ../libisomd5.a
ar cqs ../libisomd5.a libcheckisomd5.o md5.o
make[2]: Leaving directory '/home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/lib/isomd5'
make[1]: Leaving directory '/home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/lib'
cd app/ && ( test -e Makefile || /usr/bin/qmake-qt5 /home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/app/app.pro PREFIX=/usr -o Makefile ) && make -f Makefile 
cd helper/ && ( test -e Makefile || /usr/bin/qmake-qt5 /home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/helper/helper.pro PREFIX=/usr -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/helper'
cd linux/ && ( test -e Makefile || /usr/bin/qmake-qt5 /home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/helper/linux/linux.pro PREFIX=/usr -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/app'
g++ -c -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DBINDIR=\"/usr/bin\" -DDATADIR=\"/usr/share\" -DLIBEXECDIR=\"/usr/libexec/mediawriter\" -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../lib -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o main.o main.cpp
g++ -c -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DBINDIR=\"/usr/bin\" -DDATADIR=\"/usr/share\" -DLIBEXECDIR=\"/usr/libexec/mediawriter\" -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../lib -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o drivemanager.o drivemanager.cpp
g++ -c -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DBINDIR=\"/usr/bin\" -DDATADIR=\"/usr/share\" -DLIBEXECDIR=\"/usr/libexec/mediawriter\" -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../lib -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o releasemanager.o releasemanager.cpp
g++ -c -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DBINDIR=\"/usr/bin\" -DDATADIR=\"/usr/share\" -DLIBEXECDIR=\"/usr/libexec/mediawriter\" -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../lib -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o utilities.o utilities.cpp
g++ -c -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DBINDIR=\"/usr/bin\" -DDATADIR=\"/usr/share\" -DLIBEXECDIR=\"/usr/libexec/mediawriter\" -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../lib -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o fakedrivemanager.o fakedrivemanager.cpp
g++ -c -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DBINDIR=\"/usr/bin\" -DDATADIR=\"/usr/share\" -DLIBEXECDIR=\"/usr/libexec/mediawriter\" -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../lib -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o options.o options.cpp
g++ -c -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DBINDIR=\"/usr/bin\" -DDATADIR=\"/usr/share\" -DLIBEXECDIR=\"/usr/libexec/mediawriter\" -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../lib -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o linuxdrivemanager.o linuxdrivemanager.cpp
make[2]: Entering directory '/home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/helper/linux'
g++ -c -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DBINDIR=\"/usr/bin\" -DDATADIR=\"/usr/share\" -DLIBEXECDIR=\"/usr/libexec/mediawriter\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../../lib -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o main.o main.cpp
/usr/lib64/qt5/bin/rcc -name qml qml.qrc -o qrc_qml.cpp
/usr/lib64/qt5/bin/rcc -name assets assets.qrc -o qrc_assets.cpp
/usr/lib64/qt5/bin/rcc -name translations ../translations/translations.qrc -o qrc_translations.cpp
RCC: Error in '../translations/translations.qrc': Cannot find file 'cs.po'
Makefile:371: recipe for target 'qrc_translations.cpp' failed
make[1]: *** [qrc_translations.cpp] Error 1
make[1]: *** Waiting for unfinished jobs....
g++ -c -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DBINDIR=\"/usr/bin\" -DDATADIR=\"/usr/share\" -DLIBEXECDIR=\"/usr/libexec/mediawriter\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../../lib -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o writejob.o writejob.cpp
g++ -c -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DBINDIR=\"/usr/bin\" -DDATADIR=\"/usr/share\" -DLIBEXECDIR=\"/usr/libexec/mediawriter\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../../lib -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o restorejob.o restorejob.cpp
g++ -pipe -O2 -std=gnu++0x -Wall -W -dM -E -o moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
/usr/lib64/qt5/bin/moc -DBINDIR=\"/usr/bin\" -DDATADIR=\"/usr/share\" -DLIBEXECDIR=\"/usr/libexec/mediawriter\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/helper/linux -I/home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/lib -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include writejob.h -o moc_writejob.cpp
/usr/lib64/qt5/bin/moc -DBINDIR=\"/usr/bin\" -DDATADIR=\"/usr/share\" -DLIBEXECDIR=\"/usr/libexec/mediawriter\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/helper/linux -I/home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/lib -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include restorejob.h -o moc_restorejob.cpp
g++ -c -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DBINDIR=\"/usr/bin\" -DDATADIR=\"/usr/share\" -DLIBEXECDIR=\"/usr/libexec/mediawriter\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../../lib -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o moc_writejob.o moc_writejob.cpp
g++ -c -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DBINDIR=\"/usr/bin\" -DDATADIR=\"/usr/share\" -DLIBEXECDIR=\"/usr/libexec/mediawriter\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../../lib -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o moc_restorejob.o moc_restorejob.cpp
linuxdrivemanager.cpp: In member function ‘void LinuxDrive::onFinished(int, QProcess::ExitStatus)’:
linuxdrivemanager.cpp:216:64: warning: unused parameter ‘status’ [-Wunused-parameter]
 void LinuxDrive::onFinished(int exitCode, QProcess::ExitStatus status) {
                                                                ^~~~~~
linuxdrivemanager.cpp: In member function ‘void LinuxDrive::onRestoreFinished(int, QProcess::ExitStatus)’:
linuxdrivemanager.cpp:226:71: warning: unused parameter ‘status’ [-Wunused-parameter]
 void LinuxDrive::onRestoreFinished(int exitCode, QProcess::ExitStatus status) {
                                                                       ^~~~~~
linuxdrivemanager.cpp: In member function ‘void LinuxDrive::onErrorOccurred(QProcess::ProcessError)’:
linuxdrivemanager.cpp:236:57: warning: unused parameter ‘e’ [-Wunused-parameter]
 void LinuxDrive::onErrorOccurred(QProcess::ProcessError e) {
                                                         ^
g++ -Wl,-O1 -o helper main.o writejob.o restorejob.o moc_writejob.o moc_restorejob.o   -L/home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/lib -lisomd5 -lQt5Gui -lQt5Network -lQt5DBus -lQt5Core -lGL -lpthread 
make[2]: Leaving directory '/home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/helper/linux'
make[1]: Leaving directory '/home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/helper'
make[1]: Leaving directory '/home/osezer/Downloads/mediwriter/MediaWriter-3.96.1/app'
Makefile:69: recipe for target 'sub-app-make_first' failed
make: *** [sub-app-make_first] Error 2

**Comment by thunderbirdtr** [comment]
After I made "make install" and run "mediawriter" result is ; 

Warning: QQmlApplicationEngine failed to load component ((null):0, (null))
Warning: qrc:/main.qml:24 module "QtQuick.Dialogs" is not installed
qrc:/main.qml:25 module "QtQuick.Layouts" is not installed
qrc:/main.qml:21 module "QtQuick.Controls" is not installed
qrc:/main.qml:22 module "QtQuick.Controls.Styles" is not installed
qrc:/main.qml:24 module "QtQuick.Dialogs" is not installed
qrc:/main.qml:25 module "QtQuick.Layouts" is not installed
qrc:/main.qml:21 module "QtQuick.Controls" is not installed
qrc:/main.qml:22 module "QtQuick.Controls.Styles" is not installed
qrc:/main.qml:24 module "QtQuick.Dialogs" is not installed
qrc:/main.qml:25 module "QtQuick.Layouts" is not installed
qrc:/main.qml:21 module "QtQuick.Controls" is not installed
qrc:/main.qml:22 module "QtQuick.Controls.Styles" is not installed
qrc:/main.qml:24 module "QtQuick.Dialogs" is not installed
qrc:/main.qml:25 module "QtQuick.Layouts" is not installed
qrc:/main.qml:21 module "QtQuick.Controls" is not installed
qrc:/main.qml:22 module "QtQuick.Controls.Styles" is not installed
 ((null):0, (null))

**Comment by thunderbirdtr** [comment]
After I checked the source code itself , looks like file-name problem already fixed, still even i compiled in master branch, it ended same as my second comment.

**Comment by MartinBriza** [comment]
Hello, sorry for the bug from your first comment, I made a typo in the script to generate the .rc file. It is okay now as you noticed (Fixed in 3cbb96ed6987a2d0d68b461ebdd27c4a3361dcd4 ).
In regards to your second comment: You don't have the qt5-qtquickcontrols package installed.

**Comment by thunderbirdtr** [comment]
I thought I installed all of it but looks like I forgat that one. I'm sorry it's fixed now.
