### ISSUE TITLE
L10N - string we should or should not have

### ISSUE THREAD

**Issue by Jibec** [MartinBriza/MediaWriter#18]
Hi,

We probably do not need to translate:
- https://github.com/MartinBriza/MediaWriter/blob/master/dist/linux/mediawriter.desktop#L34 if someone translate it by mistake, it would probably not run. Or is it done on purpose ?

We probably need to translate
- https://github.com/MartinBriza/MediaWriter/blob/master/app/utilities.cpp#L313 even if only displayed in log file.
- https://github.com/MartinBriza/MediaWriter/blob/master/app/components/DownloadDialog.qml#L197 as B/KB/GB have different ways of writing across languages. It would be better to have multiple sentences like "%1 B left", "%1 KB left", etc. It's a good practice not to cut strings because many languages do not have same order than English, it make translator work easier.

thanks a lot for your help

**Comment by MartinBriza** [comment]
Hello, thanks for the report!
Just one question, should we translate the "KB", "MB", etc. too? Or do I need to keep just the word order in mind?

**Comment by Jibec** [comment]
Yes, we should translate it too !

**Comment by MartinBriza** [comment]
Ok, thanks, I'm just working on it.
The string from the desktop file will be a bit of a problem because xgettext just keeps on extracting it for some reason. I'll probably just grep it out to be safe...
