### ISSUE TITLE
show a notification when writing is complete

### ISSUE THREAD

**Issue by kparal** [MartinBriza/MediaWriter#20]
Writing a USB stick is a long-lasting task. It would be awesome if you could send a desktop notification once the writing is done. The same way apps like Nautilus do it (at least in GNOME) once I/O operations are done. Just an idea.

**Comment by MartinBriza** [comment]
That's a good and valid idea. However displaying notifications in Qt is not a thing that would be platform-independent so I'd have to solve it for all three platforms separately.
I'll leave this open and possibly look into it in the future.
