### ISSUE TITLE
helper.exe stopped working when about to write

### ISSUE THREAD

**Issue by TruboXL** [MartinBriza/MediaWriter#22]
Maybe related to #21 
Windows 7 Ultimate SP1 x64
All the VC++ installed...

When Media Writer starts to write, a Windows Error Report dialog shows up saying "helper has stopped working"...

Tested on Workstation option and Custom ISO option, others didn't test, download speed and verifying process (uses ~11% CPU?) are very slow, so assume they will hit the helper.exe problem eventually...

Closer inspection with Process Explorer shows helper.exe runs this command (this is Custom ISO option):
`"C:\Program Files (x86)\Fedora Media Writer\helper.exe"  write D:/Downloads/F24-x86_64-MATE-20161023.iso 1`

Running it on cmd.exe returns -1 and then the same WER appear...

>Problem Event Name:	APPCRASH
>Application Name:	helper.exe
>Application Version:	0.0.0.0
>Application Timestamp:	58172358
>Fault Module Name:	KERNELBASE.dll
>Fault Module Version:	6.1.7601.23543
>Fault Module Timestamp:	57d2f948
>Exception Code:	c0000005
>Exception Offset:	0000d2ea
>OS Version:	6.1.7601.2.1.0.256.1
>Locale ID:	17417
>Additional Information 1:	0a9e
>Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
>Additional Information 3:	0a9e
>Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by MartinBriza** [comment]
Which version were you running? Where did you download it from? 
I don't understand the bits about the downloading and verification speed. Did you write a custom image or one downloaded by the FMW directly?
Did the error happen immediately after you started the writing process or after a while?

**Comment by TruboXL** [comment]
Version is 4.0.0, downloaded from [the release page](https://github.com/MartinBriza/MediaWriter/releases)

The downloading process is through Workstation option, it would be better if there's an option just use a locally downloaded ISO and just skip downloading... Just blame my ISP...

But after downloading, verifying the ISO took a long time finish using 11% of my CPU, dunno why...

The real problem is after that long time, it stopped with that WER dialog, my USB just barely flashes...
Nothing has written. Tried another one USB, same problem.

**Comment by MartinBriza** [comment]
Thanks for the description, I'll look if there's any reason for that error you're describing. It's not related to #21 though, I'd say.

The check takes only 11% of your CPU because it's reading the data from your disk which is probably not supplying the data fast enough to load the CPU to 100%.

**Comment by MartinBriza** [comment]
As I mentioned in the other issue, I'll have to get a Win7 box first to try this myself, please wait for a bit.

**Comment by MartinBriza** [comment]
I'm able to reproduce this problem, going to work on fixing it today.

**Comment by TruboXL** [comment]
Just to say, thanks for fixing it :D

**Comment by MartinBriza** [comment]
I'm glad it works for you. :)
Please come back to report any other problem you see :)
