### ISSUE TITLE
mediawriter tries to download non-existent file https://fedoraproject.org/releases.json

### ISSUE THREAD

**Issue by tyll** [MartinBriza/MediaWriter#23]
When I start mediawriter, it tries do download https://fedoraproject.org/releases.json but the file does not exist:

```
$ mediawriter 
Warning: Error QNetworkReply::NetworkError(ContentNotFoundError) reading from QUrl("https://fedoraproject.org/releases.json") : "Error transferring https://fedoraproject.org/releases.json - server replied: Not Found" ((null):0, (null))
Warning: Was not able to fetch new releases: "Error transferring https://fedoraproject.org/releases.json - server replied: Not Found" Retrying in 10 seconds. ((null):0, (null))
$ curl -I https://fedoraproject.org/releases.json
HTTP/1.1 404 Not Found
....
```

**Comment by MartinBriza** [comment]
Thanks for the report. As I said in #24, this is intentional behavior - the file is going to be hosted at that location. The scripts to generate it are not in place yet though.

**Comment by tyll** [comment]
Could you please just put an empty file there or even better one with a comment to make sure that people do not have extra work reporting a known issue?

**Comment by MartinBriza** [comment]
Yeah, it would. However, I personally don't have the access to the server and I've been trying to get this resolved for weeks. Sorry for the inconvenience.
