### ISSUE TITLE
"Checking for new releases"

### ISSUE THREAD

**Issue by satellitee** [MartinBriza/MediaWriter#24]
https://github.com/MartinBriza/MediaWriter/releases/download/4.0.0/FedoraMediaWriter-win32-4.0.0.exe 

windows mediawriter 4.0.0 does not offer 32 bit or f23 selections for download...f24 cinnamon workstation 4.0.0-2 does
both have "Checking for new releases" under Custom Image
mac offers f23 f24 - 64/32 bit intel and arm7 f24
arm7 is custom image only
=====
on #fedora-rel:
<dgilmore> mbriza: Warning: Was not able to fetch new releases: "Error transferring https://fedoraproject.org/releases.json - server replied: Not Found" Retrying in 10 seconds. ((null):0, (null))
<dgilmore> mbriza: what/who are you expecting to put something there?
<dgilmore> and how was that url arrived at?
<satellit> Mediawriter  fc24 4.0.0-2.fc24  does not give this error
* cstratak (~cstratak@a03-0223a.kn.vutbr.cz) has joined #fedora-releng

* satellit windows mediawriter also says checking for new releases  but downloads spins and labs 
* nirik points to https://admin.fedoraproject.org/pkgdb/api/collections/ instead. 
<dgilmore> 931930
<dgilmore> nirik: well it needs to get the images in releases
<dgilmore> I am not sure what it is actually expecting
<nirik> ok. dunno either
<dgilmore> seems like some communications have been forgotten
* dgilmore is only finding out because he got asked to go look at his ex wifes uncles computer 
* dgilmore suspects they have ransomware installed
<dgilmore> so figured using a live to inspect the system is a good idea
* satellit I suspect that this is a placeholder for f25 release lives when they are added..?
<dgilmore> satellit: maybe
<dgilmore> your guess is as good as mine
<dgilmore> thats why I asked mbriza
<dgilmore> we probably should sort it out this week

**Comment by MartinBriza** [comment]
This is a non-issue. Ricky Elrod is working on putting the file in place at the location FMW is expecting. It's not there yet, therefore FMW tries to download it again and again. This is by design.
