### ISSUE TITLE
https://fedoraproject.org/releases.json doesn't exist

### ISSUE THREAD

**Issue by Ancurio** [MartinBriza/MediaWriter#27]
MediaWriter seems to be continuously querying the above url, but the server responds with "Not Found":

`Warning: Was not able to fetch new releases: "Error transferring https://fedoraproject.org/releases.json - server replied: Not Found" Retrying in 10 seconds. ((null):0, (null))`

Edit: Forgot to mention: This is on the latest release available on Fedora 24 (`mediawriter-4.0.0-2.fc24.x86_64`)

**Comment by MartinBriza** [comment]
Thank you for the report. The file you mentioned in the report should appear at the location pretty soon. It's not a bug, the file has just not been generated yet. Please wait for a bit and the error message will disappear :)
