### ISSUE TITLE
MBR partition scheme for BIOS or UEFI ( Unallocated )

### ISSUE THREAD

**Issue by DeathRowRecords** [MartinBriza/MediaWriter#29]
The media check is complete, the result is: FAIL

It is not recommended to use this media.
[FAILED] Failed to start Media check on /dev . . . /by-label/Fedora-WS-Live-25-1-3.
See 'systemctl status "checkisomd5@dev-...25\\x2d1\\x2d3.service"' for details.
[     14.929069] dracut-initqueue[491] : Job for checkisomd5@dev-disk-by\x2dlabel-F
edora\x2dWS\x2dLive\x2d25\x2d1\2xd3.service failed because the control process e
xited with error code.
[     14.929613] dracut-initqueue[491] : See "systemctl status "checkisomd5@dev-dis
k-by\\x2dlabel-Fedora\\x2dWS\\x2dLive\\x2d25\\x2d1\\x2d3.service"" and "journalc
tl  -xe" for details.
[     15.039015] dracut : FATAL: CD check failed
[     15.039110] dracut : Refusing to continue
[     16.358054] : System halted

With Fedora Live USB works fine.

**Comment by MartinBriza** [comment]
Can you please give a bit more details on your system, the flash drive and the exact procedure how you wrote the image?

**Comment by DeathRowRecords** [comment]
-_-#

// Magic Ingredients

System: Fedora_24_x64
System: Window$_10_x64 <--- the "s" is silent ( $hitty, worthless )
Micro SD 4GB ( [it belongs in a museum](https://img.pandawhale.com/post-23672-Indiana-Jones-that-belongs-in-UoAL.gif), aging ungracefully, but still kickin, die hard trooper ) 
Fedora ISO ( torrent download )
Fedora Media Writer 

// Go with the flow "Short Story Telling" 

Click on Custom OS option . . . add ISO, hit next . . . . . . gracefully and stylish in appearance Loading bar, then, pleasingly and ingenious yet simple verifying data. [SUCCESS! ](http://www.bhmpics.com/walls/success_kid-other.jpg) Lil Sneak Peek -_-? De What F@#$?!.. 2 out of 3   partition where unallocated. Very Well Boot the goddamn thing . . .  and like i was mentioned my first post? feedback? issue! Ancient Relic appear :(  

This is What happen, True Story!

                                                                                                                                                     End of Story

**Comment by MartinBriza** [comment]
Ok. This is most likely caused (especially if this happens at 4.8% of media check) by the fact Windows messes up with your drive (it creates a "System Volume Information" folder on it) which then breaks its checksum.
I'm trying to solve this, however I was unable to do so yet.
If you want to make sure this doesn't happen, disconnect the flash drive right after FMW is done writing (and checking it) and reconnect it when the computer is turned off.

**Comment by MartinBriza** [comment]
Hello, can you please try this file? I have rewritten the Windows writing code and I need to verify it works better now.
http://mbriza.fedorapeople.org/FedoraMediaWriter-win32-4.0.7-4-g7cc3c2b.exe

**Comment by DeathRowRecords** [comment]
Hi Martin 
I Like Your Professionalism :) You a Cool Guy, Give me 24h ( Coz I'm Busy like a Busy lil Bee ) Downloading MS Window$ 10  . . . [Loading](https://youtu.be/HNwnz0IIsJE) I'M HAPPY 2 HELP!

**Comment by DeathRowRecords** [comment]
[Sup Martin.
](https://youtu.be/wYwSu4drOn0)
[Me](http://designwebkit.com/wp-content/uploads/2012/11/funny-dog-computer-17.gif)
How many of us everyday developers resonate with this quote "**_My code is awesome_**" well this is a quote that we should also look at and respect "**_History is a vast early warning system_**" and that's the point of this talk.

Yes, code hygiene matters! 

`for (size_t i = 0; i < prefixes.size(); i++) {
       if  (StrUtils::StartsWith(id, prefixes[i])**,** true) {
       {
            return true;
        }
 }` 

[Did you spot the problem? . . .](http://www.dumpaday.com/wp-content/uploads/2012/12/funny-math-questions.jpg) 

"**,**" so this **if** statement actually consists of two expressions, separated with a comment the second one is true, so this if statement actually is **_if true_**. 

// Back to Fedora Media Writer ( things I've noticed )

A: Duplicate Bug ( detects generic memory card, but no card inserted ) blue bar 
B: Well Your Cheep Reverse Engineering [Fix](http://img.gawkerassets.com/img/199q0oatfr8svgif/ku-xlarge.gif) the Issue for [Windows 10 ](https://youtu.be/HNwnz0IIsJE)People. ( but need some TLC )
C: is the answer for "which letter of the alphabet has the most water?
D: If that's ALL, I'm signing off 

[Friend #1](http://media.giphy.com/media/RR7aysueE4mTS/giphy.gif) [Friend #2](http://images.huffingtonpost.com/2013-03-10-chucknorrisapproves.gif) [Well you know what 2 do :D](https://static1.squarespace.com/static/52e118dae4b0a7dd7b3c8b76/t/56168f8ce4b0752eb58686b0/1444319183670/dev,+'fuck+it+ship+it'.jpg?format=1500w)

**Comment by MartinBriza** [comment]
I seriously don't understand where you're going with this report, sorry. The code you posted has nothing to do with my code and the notes at the bottom don't say anything.
If there's still a problem, please be more specific.

**Comment by MartinBriza** [comment]
Closing this issue as I don't understand what was it about unfortunately. If you still experience any issues, feel free to reopen this issue or create a new one with a more comprehensible description. Including memes and videos is fine but I struggle with street English, sorry :(
