### ISSUE TITLE
Language is in Bulgarian (macOS Sierra)

### ISSUE THREAD

**Issue by alanorth** [MartinBriza/MediaWriter#32]
I have several keyboards installed (including Bulgarian) and the installer launches in Bulgarian language with no way to change it. I tried switching keyboards before launching the tool, uninstalling all non-English keyboards, etc, but the language is always Bulgarian.

This is version 4.0.7 from the [Fedora release page](https://getfedora.org/workstation/download/).

**Comment by MartinBriza** [comment]
Thank you for the report. Qt for some reason chooses the secondary language instead of the primary one for the FMW UI. I'll have to change this in the next version.

**Comment by headius** [comment]
May be a dupe: https://github.com/MartinBriza/MediaWriter/issues/51

Has this fix gone into a release?
