### ISSUE TITLE
Buggy detection of mounted flash drive

### ISSUE THREAD

**Issue by nfsmaniac** [MartinBriza/MediaWriter#36]
Hi,
I've just tried the MediaWriter. I haven't mounted any flash drive yet but application thinks that yes.
I have an internal memory card reader in desktop PC, but no card inserted.

See the blue message (and the Exabyte size): 😄 
![fedora_mw](https://cloud.githubusercontent.com/assets/3188999/20571689/cd8992d8-b1a8-11e6-87cc-f7589fec6201.png)

Win 8.1 x86-64

**Comment by MartinBriza** [comment]
What a peculiar bug, thanks for the report. :)

**Comment by nfsmaniac** [comment]
You're welcome. ;-)
And thanks for fixing the bug.

**Comment by mikedep333** [comment]
I'm running 4.0.7 and  I see this (0 bytes) on my empty SD card reader:
![2016-12-04 08_50_59-fedora media writer](https://cloud.githubusercontent.com/assets/1698741/20866611/db3a6656-b9fe-11e6-812d-5c8e437777a4.png)
This system runs Windows 10 1607. 
It is the USB SD card reader in my Dell U2713H monitor. Windows identifies the card reader as:
> USBSTOR\DiskGeneric-SD/MMC/MS/MSPRO_1.00

**Comment by MartinBriza** [comment]
This should be fixed with 4.0.8. Please reopen this issue if your problem persists.
