### ISSUE TITLE
no logs; crashes; no cache of download; some USB's not detected

### ISSUE THREAD

**Issue by NatureMuncher** [MartinBriza/MediaWriter#38]
MacOS Sierra 
tried four USB flash drives, two were undetected despite formatting them for various filesystems. The tool kept reporting `There are no portable drives connected.` 
While downloading, it crashed on several occasions. Each time when restarting it had to start at the beginning. Several times it just failed with a corrupt download for unknown reasons.
During the period I am able to download the official ISO so I don't think it's a connectivity issue.
Not seeing any info on logfile location and nothing in the console is tagged with `fedora` or `media` so not sure where to start to provide more useful debugging info.

**Comment by MartinBriza** [comment]
Hello,
I'm sorry about the problems. 
If you want to help me find the underlying problem, please click the "Report..." button when the crash happens again and send me the whole log that's in there. Or put it here.

**Comment by MartinBriza** [comment]
This should be fixed with 4.0.8. Please reopen this issue if your problem persists.
