### ISSUE TITLE
Windows 10 Fedora 25 Issue

### ISSUE THREAD

**Issue by damaestro** [MartinBriza/MediaWriter#39]
Testing a next, next for Fedora Workstation 25, the resulting boot does not pass media checking. Using all of the same hardware and the f25 mediacreator, boot passes media check. Using the same image and `livecd-iso-to-disk` passes media checks.

This was reported in freenode#fedora and I was able to confirm with a fully updated Windows 10 install using known good hardware and the latest build from https://getfedora.org/en/workstation/download/

**Comment by MartinBriza** [comment]
Yes, on some configurations Windows writes data to the drive (to be precise, it mounts it and creates a "System Volume Information" folder). This won't affect the functionality of the live drive (you can boot and it will work just fine if the media check in FMW passed) but the online media check fails.
I'm trying to solve this.

**Comment by MartinBriza** [comment]
Hello, can you please try this file? I have rewritten the Windows writing code and I need to verify it works better now.
http://mbriza.fedorapeople.org/FedoraMediaWriter-win32-4.0.7-4-g7cc3c2b.exe

**Comment by damaestro** [comment]
There was a strange permission denied error on first attempt but an immediately followed attempt worked and the media passed checks. Confirmed by two people.

**Comment by MartinBriza** [comment]
This should be fixed with 4.0.8. Please reopen this issue if your problem persists.
