### ISSUE TITLE
Destination drive is not writable

### ISSUE THREAD

**Issue by UncleInf** [MartinBriza/MediaWriter#40]
Tried installing fedora 25 on usb, but always getting this error:

> Destination drive is not writable

 Windows 10 x64. This is what gets created:

![mediawriter partitions](https://cloud.githubusercontent.com/assets/9434565/20632072/7aa6c1c0-b343-11e6-8ed1-5bdb104ea42d.png)

**Comment by MartinBriza** [comment]
I'm working to improve the Windows writing code. I think your issue will be gone in the next version.

If you hit this issue, please as a workaround, start the Command Prompt (Admin) and run "diskpart" in it.
There use "list disk" which will print disk numbers and find which one is your drive (probably 1).
Then use "select disk <number>", probably "select disk 1".
Then use "clean".
Now your drive should work fine in FMW. If not, please wait for the update, I'll keep you posted.

**Comment by UncleInf** [comment]
I dont think the workaround worked, I guess ill wait for the update :)

**Comment by MartinBriza** [comment]
Hello, can you please try this file? I have rewritten the Windows writing code and I need to verify it works better now.
http://mbriza.fedorapeople.org/FedoraMediaWriter-win32-4.0.7-4-g7cc3c2b.exe

**Comment by UncleInf** [comment]
I've restored drive to factory settings using this tool (all worked okay - drive is visible to windows, one fat partition) but when trying installation this time I get error:
>Destination drive is not writable (Access is denied)
>Couldn't open drive for writing (Access is denied)
>Couldn't lock the drive (The handle is invalid)

After this, the partition table is the same as in first picture: 45mb (unallocated), 5mb (anaconda) and rest is unallocated

Version: 4.0.7-4-g7cc3c2b

**Comment by MartinBriza** [comment]
That's not good news. Thanks for testing. I'll work on this problem tomorrow or some time next week and get in touch again.
Btw did this problem happen right after you restored the drive? By this I mean: you restored it and went to write to it immediately?

**Comment by UncleInf** [comment]
I am happy to help. Yes, I did restore and immediately went to write it. I believe in one of quite few test cases I did open drive in windows or looked at partitions with another program before writing, but not all the times.

**Comment by UncleInf** [comment]
After numerous tries the program started working a bit more. By that I mean it completed loading bar to the end and then I got error:

> Destination drive is not writable (The parameter is incorrect)
> Couldn't open drive for writing (Access is denied)
> Couldn't lock the drive (The handle is invalid)

This "new" error came up after me trying the unebootin to make bootable usb. Sadly it didn't boot and I tried media writer again and got that.

Now the funny thing is that I cannot reproduce it without unebootin - I've tried formatting usb, setting partition active, writing to it, formatting with windows. Nothing. After unebootin install I try with media writer and boom. 

Even though the error changes, the partition table is the same as before. Another funny thing is during install usb drive flashes as if it is written to. When the bar completes is takes some time before the error pops out and right before popping out the driver flashes. 

That's all the bit and pieces I've come up.

**Comment by MartinBriza** [comment]
This should be fixed with 4.0.8. Please reopen this issue if your problem persists.

**Comment by jcshelby** [comment]
I'm also having this issue on v4.1.1 attempting to install Fedora 28 xfce on a USB drive. I tried two different drives, both cleaned and formatted, and am still having the same issue. The error message is the same for me as it was in the original issue for which this thread was opened. Please let me know what information I can provide to assist with troubleshooting this and I'll be glad to do so. Thanks!

**Comment by iamliammckimm** [comment]
I'm also having this issue with the latest version from the website.
