### ISSUE TITLE
SanDisk Cruzer Edge Media drive not listed on Mac

### ISSUE THREAD

**Issue by brianhuk** [MartinBriza/MediaWriter#42]
I have tried to use MediaWriter on a macbook pro running macos Sierra to create a Fedora image on a SanDisk Cruzer Edge Media 16GB drive. The SanDisk device does not show up and I only see the meesage 'There are no portable drives connected'.

**Comment by MartinBriza** [comment]
Hello, thanks for the report. Windows seems to not treat some Sandisk drives as portable drives...
I've got one Sandisk Extreme here that didn't show up in FMW either and I'm fixing the code right now.

**Comment by MartinBriza** [comment]
Hmmm, for some reason I thought this was for Windows. Reopening

**Comment by brianhuk** [comment]
Thanks, I was going to respond to confirm I was using a mac but could not find the time.
