### ISSUE TITLE
Cannot create media over an external USB 3 hard disk

### ISSUE THREAD

**Issue by andhdo** [MartinBriza/MediaWriter#43]
an external hard drive is mounted in windows 10. Then the mediaWriter application starts and the "customized image" option is selected. A fedora 25 atomic distribution iso is selected, but there is no choice to find the hard drive mounted previosly. Seems that only "removable drives" can be used for this task, but the external hard drive is not recognized to "burn".

[universal usb installer] ( https://www.pendrivelinux.com/universal-usb-installer-easy-as-1-2-3/ ) does have this option instead, but with a tag that indicates that it could be used with caution.

**Comment by MartinBriza** [comment]
Thank you for the report. This problem will be fixed in the following release.
