### ISSUE TITLE
Fedora Media Writer 4.0.7 for Windows crashes on launch on Windows 7

### ISSUE THREAD

**Issue by wes-novack** [MartinBriza/MediaWriter#44]
After installing Fedora Media Writer and attempting to launch it on Windows 7 SP1 Professional 64-bit, I immediately get a crash dialog box titled "Microsoft Visual C++ Runtime Library" that states "This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information."

Happy to provide a screenshot if needed.

I downloaded Fedora Media Writer from here: https://getfedora.org/en/workstation/download/

Which gave me the download link: https://getfedora.org/fmw/FedoraMediaWriter-win32-4.0.7.exe

Windows Application log entry:
```
Log Name:      Application
Source:        Application Error
Date:          12/4/2016 12:37:47 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      HP-ZBook
Description:
Faulting application name: mediawriter.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: libGLESv2.dll, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x40000015
Fault offset: 0x00185e38
Faulting process id: 0x38cc
Faulting application start time: 0x01d24dffe9848ac2
Faulting application path: C:\Program Files (x86)\Fedora Media Writer\mediawriter.exe
Faulting module path: C:\Program Files (x86)\Fedora Media Writer\libGLESv2.dll
Report Id: 8cfa5de0-b9f4-11e6-98b5-5ce0c5eaf87a
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-12-04T07:37:47.000000000Z" />
    <EventRecordID>19600</EventRecordID>
    <Channel>Application</Channel>
    <Computer>HP-ZBook</Computer>
    <Security />
  </System>
  <EventData>
    <Data>mediawriter.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>00000000</Data>
    <Data>libGLESv2.dll</Data>
    <Data>0.0.0.0</Data>
    <Data>00000000</Data>
    <Data>40000015</Data>
    <Data>00185e38</Data>
    <Data>38cc</Data>
    <Data>01d24dffe9848ac2</Data>
    <Data>C:\Program Files (x86)\Fedora Media Writer\mediawriter.exe</Data>
    <Data>C:\Program Files (x86)\Fedora Media Writer\libGLESv2.dll</Data>
    <Data>8cfa5de0-b9f4-11e6-98b5-5ce0c5eaf87a</Data>
  </EventData>
</Event>
```

**Comment by DieselNomad** [comment]
Same happens here with Windows 7 Professional with latest updates on Lenovo W500

Real bummer as alternative routes to get a bootable USB stick took me 2 hours to get something working.
This for Fedora 17 reverting to LiveUSBCreator.

Would be beneficial to the distribution of Fedora among Win7 users to get this fixed,

**Comment by MartinBriza** [comment]
It works on Windows 7 for most people, as far as I know. What you are
experiencing is probably a problem with some libraries or even drivers.
I'll work on this problem next week, getting a few more Win7 instances to
try on.

2016-12-10 11:46 GMT+01:00 DieselNomad <notifications@github.com>:

**Comment by MartinBriza** [comment]
Please follow issue #21  where I'll track the fixing of this problem.

**Comment by kwoodle** [comment]
After installing Fedora Media Writer and attempting to launch it on Windows 7 SP1 Professional 64-bit, I immediately get a crash dialog box titled "Microsoft Visual C++ Runtime Library" that states "This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information."
Faulting application name: mediawriter.exe, version: 0.0.0.0, time stamp: 0x5874d4ee
Faulting module name: libGLESv2.dll, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x40000015
Fault offset: 0x00185e38
Faulting process id: 0x43c
Faulting application start time: 0x01d2b4acaca49642
Faulting application path: C:\Program Files (x86)\Fedora Media Writer\mediawriter.exe
Faulting module path: C:\Program Files (x86)\Fedora Media Writer\libGLESv2.dll
Report Id: ee99bff9-209f-11e7-a9d5-4ccc6a8fe1d0

**Comment by MartinBriza** [comment]
Can you please specify the graphics hardware you're using and if possible,
also the driver version?

2017-04-14 1:27 GMT+02:00 kwoodle <notifications@github.com>:

**Comment by kwoodle** [comment]
Nvidia GeForce GTX 750 Driver version 378.49
Thanks

**Comment by MartinBriza** [comment]
Hmmm, that's pretty new, it should work fine. Did this happen with the
4.0.95 version from the Releases section here on Github?

2017-04-26 14:57 GMT+02:00 kwoodle <notifications@github.com>:
