### ISSUE TITLE
Created USB is unusable with ROM boot

### ISSUE THREAD

**Issue by wvxvw** [MartinBriza/MediaWriter#46]
Today I've tried to install Fedora 25 alongside Windows 7. Windows 7 is installed in a way that it doesn't have EFI partition, but created live USB attempts only to create EFI boot (and fails with irrelevant errors, s.a. reporting zero free disk space, while there are 500 GiB free space).

I don't know where to begin to collect information for this bug: there are so many things broken at the same time.

**Comment by MartinBriza** [comment]
Hello.
So you mean you booted to Fedora using the live media created by Fedora
Media Writer and then installed Fedora alogside of your Windows
installation? In that case that's a problem of the installer in the live
image (anaconda) or just the settings you chose during the installation.
If you used Fedora Media Writer to write Fedora to an external drive where
you already had a Windows installation, Fedora took the whole drive for
itself.
In both cases there's no way I can assist you unfortunately.
Can you please go more in detail about the process you used to achieve the
problem you have now?

2016-12-10 17:19 GMT+01:00 wvxvw <notifications@github.com>:

**Comment by MartinBriza** [comment]
Not a FMW issue, closing. There's a RFE open requesting a feature that would solve your problem: #41
I'm not going to implement that any time soon though.
