### ISSUE TITLE
MediaWriter freezes

### ISSUE THREAD

**Issue by Acru2015** [MartinBriza/MediaWriter#47]
Today I wanted to create a bootable Ubuntu stick with the MediaWriter.
When I selected the ISO the selection screen closed normally but immediately afterwards the system froze. I tried it a second time after restarting, but the same happened. I then tried it with XORG where it still froze but I was still able to move the mouse. The fourth time I started regularly again but with journalctl -e on another terminal. This time only MediaWriter froze, and I got a lot of output in the journal, mostly looking like this:

Dec 14 11:12:36 Acru2015-PC kernel: nouveau 0000:01:00.0: gr: ILLEGAL_CLASS ch 10 [007ee85000 Xwayland[1706]] subc 0 class 090c mthd 1b0c data 1000f010

The output of MediaWriter showed nothing.

I then tried to create a regular Fedora bootstick, where it froze the system again a few seconds into the download. On a side note my youtube music resumed regularly.

I am running an up-to-date Fedora 25 with Gnome Wayland.

**Comment by MartinBriza** [comment]
Yeah, sorry about that. This is a driver problem (or maybe even Qt bug) with nouveau. You could try running it with QSG_RENDER_LOOP=basic  which could fix your problem but also cause some other issues.
However, there unfortunately is nothing I can do about the problem. This has to be solved either in Qt or in the nouveau driver itself.

**Comment by Acru2015** [comment]
Ok, thank you for the quick reply!
