### ISSUE TITLE
Security question: Are the downloaded images cryptographically verified?

### ISSUE THREAD

**Issue by nightvisi0n** [MartinBriza/MediaWriter#48]
Unfortunately I can't find any notice whether the downloaded images are verified for security and integrity like [proposed by fedora](https://getfedora.org/en/verify) itself?

**Comment by MartinBriza** [comment]
Yes, the SHA256 checksum is computed on the fly during the download and
verified right after it's finished. The "verifying" phase after download
then checks the embedded MD5 checksum of the .iso file for its integrity.
I hope that answers your question. If you have further concerns, please let
me know.

2016-12-15 16:12 GMT+01:00 Julian <notifications@github.com>:

**Comment by jneureuther** [comment]
Thank you for the clarification.
Would it be possible to add a note about this to the readme? I think many fedora users are interested about the security/integrity of what they download.
Additionally I would propose to cryptographically verify the downloaded images. Had there already been any thoughts about this topic?

**Comment by nightvisi0n** [comment]
@MartinBriza Any thoughts on my comments?

**Comment by MartinBriza** [comment]
I'll add a note about it in the readme. I'll also ship a brief readme with the Windows program, maybe even the macOS one if I find out a plausible way how to do that.

What exactly do you mean by cryptographically verifying the images? The sha256 hash is included in the FMW metadata and computed while the file is downloaded ( see https://github.com/MartinBriza/MediaWriter/blob/master/app/assets/releases.json , https://github.com/MartinBriza/MediaWriter/blob/master/app/utilities.cpp#L325 and https://github.com/MartinBriza/MediaWriter/blob/master/app/releasemanager.cpp#L645 for reference ). Is this not enough? Do you mean some other way of doing it?
