### ISSUE TITLE
Direct portable media writing support for other USB devices

### ISSUE THREAD

**Issue by hopparz** [MartinBriza/MediaWriter#49]
When I starting the Fedora Media Writer, and asking for download, the app doesn't detects what kind of portable devices I have available already. Only capable to see USB HDD or SSDs, but not SD cards, pendrives, nor DVD disks. The immediate writing option under the panel only available with USB HDDs or SSDs only. 

![kijeloles_010](https://cloud.githubusercontent.com/assets/18486268/21315375/2acef606-c5fc-11e6-8d1c-d4b88bae678a.png)

**Comment by MartinBriza** [comment]
It should see pendrives and SD drives. Can you please state which drives/SD card readers do you have by using lsusb?

**Comment by hopparz** [comment]
Here is my lsusb output. This machine is an Dell Latitude 4310i, with integrated SD card reader. I usually keep big SD cards in the front drive (if there is any size limitation routine, as I guessed), but until the file handler sees, and mounts drives - this app only able to see HDDs and SSDs on my machine.

**Comment by MartinBriza** [comment]
This should be fixed with 4.0.8. Please reopen this issue if your problem persists.
