### ISSUE TITLE
Gnome Multiwrite integration

### ISSUE THREAD

**Issue by hopparz** [MartinBriza/MediaWriter#50]
We have an FOSS application called Gnome Multiwrite in repos in long time - that is capable to write out multiple USB drives, pendrives with different sources. It would be great support to the app for Ambassadors, if doesn't have to wait the visitiors till the disk gets ready.

**Comment by MartinBriza** [comment]
I don't understand the request. What way do you think the tools could be integrated, please?

**Comment by MartinBriza** [comment]
I still don't understand what's this feature request about and there has been no movement - closing the issue. However please go ahead and reopen it if you want to add more detail. Thank you.
