### ISSUE TITLE
Media Writer chooses Russian language on startup

### ISSUE THREAD

**Issue by headius** [MartinBriza/MediaWriter#51]
I'd sure love to use this thing to make a bootable USB drive...but it's starting up in Russian and I can't figure out how to change that.

![screenshot 2016-12-22 13 51 20](https://cloud.githubusercontent.com/assets/10135/21438284/c5a59556-c84d-11e6-93c5-a79ea7067687.png)

I had a Russian keyboard installed when I first ran the app, but removing it does not appear to help.

**Comment by jlfranklin** [comment]
In System Preferences, under Languages, remove all other languages.  Media Writer seems to choose the first non-English language it finds in the list.  If (in my example below), the first (primary) language is French or Japanese, FMW will choose that, but if English is the first language, FMW will choose the second one in the list.

![screen shot 2016-12-28 at 8 23 34 am](https://cloud.githubusercontent.com/assets/17887377/21522878/57fdeb0a-ccd7-11e6-97d0-611dd09903fa.png)

**Comment by MartinBriza** [comment]
Thanks, yes. This will get fixed in 4.0.8 which will be released some time this week. I'm sorry for the trouble this has caused you.

**Comment by MartinBriza** [comment]
This should be fixed with 4.0.8. Please reopen this issue if your problem persists.
