### ISSUE TITLE
Cannot write to SanDisk removable drive

### ISSUE THREAD

**Issue by jdpage** [MartinBriza/MediaWriter#54]
Platform: Windows 10
Version: 4.0.7

So for a while, SanDisk made their removable USB drives report themselves as "Fixed Disks" instead of "Removable Disks". MediaWriter therefore prevents me from writing to it. Apparently SanDisk did this to comply with Windows certification requirements, and has since reversed their position.

(sources: http://www.sevenforums.com/hardware-devices/299263-flash-stick-showing-local-disk.html and http://www.sevenforums.com/hardware-devices/326267-removable-flash-drive-recognized-local-disk-not-flash-drive-2.html#post2729627)

It'd be nice if there was a way to override this restriction, though since it affects a limited number of devices (drives made by SanDisk from 2012 through 2013), it may not be worth the risk. It may also be possible to detect devices in a different way, e.g. by checking if the device is connected to the USB bus.

**Comment by MartinBriza** [comment]
Hello, thanks for the report. This is already fixed. I'm aiming to release a new version containing the fix today or tomorrow, depending on if I discover any remaining issues when testing it.

**Comment by jdpage** [comment]
Ah, thanks! Sorry for the duplicate report; I didn't think to check in the closed issues, and I didn't see an open one.
