### ISSUE TITLE
Check media right before writing

### ISSUE THREAD

**Issue by abrodkin** [MartinBriza/MediaWriter#56]
It looks like MediaWriter checks existence of removable media only once on start.
Which leads to misleading behavior in the following scenario:
 1. Start MediaWriter
 2. Select image to write
 3. Insert a removable media (say USB flash drive)
 3. Go to "write" section and ...
 4. See `There are no portable drives connected` even though flash drive is inserted really.

**Comment by MartinBriza** [comment]
That's not true. You probably have a drive that reports itself as fixed,
not removable. This will be fixed in a release coming out today.

2017-01-09 16:52 GMT+01:00 Alexey Brodkin <notifications@github.com>:

**Comment by abrodkin** [comment]
@MartinBriza Well I tried:
 1. SD-card inserted in my laptop directly
 2. SD-card inserted in USB card-reader (in that case it is even funnier because MediaWriter allows to select either socket of that card reader regardless real card being inserted, in fact no card could be inserted at all... so this is another weak point I guess)
 3. USB flash-drive

**Comment by MartinBriza** [comment]
This should be fixed with 4.0.8. Please reopen this issue if your problem persists.
