### ISSUE TITLE
Apple Partion Map

### ISSUE THREAD

**Issue by mtennes** [MartinBriza/MediaWriter#57]
No matter how I try, Fedora Media Writer creates an _Apple partition map_ and an _Anaconda_ partition on my USB device (see below), which apparently is un-bootable on my Dell PC that I want to be my linux workstation. I am running FMW 4.0.7 and trying to install **`Fedora-Workstation-Live-x86_64-25-1.3.iso`** Here are the things I've tried:

- Manually formatting USB Flash with Disk Utility before running FMW
	- GUID Partition Map
	- Master Boot Record
- Tried 6 different USB Flash Drives from different manufacturers ALL larger than 8GB
- Tried on three different machines:
	- MacOS Sierra on MacPro
	- MacOS Sierra on MacBook Pro
	- Windows 10 on MacBook Pro )
- Manually formatting USB Flash Drive on Windows 10 before running FMW on Windows 10.

I hope I am missing something embarrassingly obvious. Please show me what that is???

![disk utilityscreensnapz001](https://cloud.githubusercontent.com/assets/4578596/21891678/dbf65570-d8a1-11e6-93a2-77d26f7a535a.jpg)

**Comment by MartinBriza** [comment]
The Apple Partition Map you see and the wrong size is completely okay.
With the list of options you tried to write the image, I suspect there's a problem with the Dell computer you're trying to install on. Are you sure you have enabled USB boot on that machine? To be extra sure everything is alright, please (if possible) try disabling the Secure Boot (UEFI) option and go for Legacy instead.

**Comment by mtennes** [comment]
All USB ports are not created equally. Although this Dell has seven USB ports, it appears only two can be used to boot the computer. All good now.

**Comment by MartinBriza** [comment]
I'm glad to hear that. If you hit any other problem, please feel free to open a new issue here and we'll see what we can do about it.
