### ISSUE TITLE
set User-Agent: Fedora Media Writer/version (platform)

### ISSUE THREAD

**Issue by mattdm** [MartinBriza/MediaWriter#58]
Right now, we are using the default user agent string, "Mozilla/5.0". It would be nice to be able to tell how popular MediaWriter is by separating out its downloads. Platform information is, of course, also useful — windows/osx/linux.

Please set User-Agent to "FedoraMediaWriter/$VERSION ($PLATFORM)" (or similar — I don't care about the exact details).

**Comment by smooge** [comment]
I would like to second this. A general amount would help clarify how long a version takes to spread out in usage and which platforms are being used.

**Comment by MartinBriza** [comment]
Great suggestion, I'll add the user agent soon, probably even today.

**Comment by mattdm** [comment]
Awesome — thanks!
