### ISSUE TITLE
Check for new versions on getfedora.org and notify users

### ISSUE THREAD

**Issue by mattdm** [MartinBriza/MediaWriter#59]
It would be nice if users were notified if there is a new version available. We'd want this to be only when there's a new version live on getfedora.org, not when there's a new release here, so I'll file a separate ticket with the web team

**Comment by mattdm** [comment]
Web team ticket: https://github.com/MartinBriza/MediaWriter/issues/59

**Comment by MartinBriza** [comment]
Can you please specify where exactly is the ticket you mentioned? I don`t seem to be able to find it anywhere.

**Comment by mattdm** [comment]
Whoops sorry. I linked the wrong thing. Edited above.

**Comment by MartinBriza** [comment]
Ok, the code is now in
