### ISSUE TITLE
Win10: Installer crashes (with disabled UAC prompts)

### ISSUE THREAD

**Issue by MartinBriza** [MartinBriza/MediaWriter#62]
Most likely related to the disabled UAC prompts, more information on this link

https://www.reddit.com/r/Fedora/comments/5ojtw8/my_user_experience_trying_to_get_fedora_on/

**Comment by MartinBriza** [comment]
I have tried disabling UAC through both the Control panel and a registry tweak and it didn't crash on me at all.
There has been some changes to how the installer is composed now so I'll close it and we'll see if anyone reports this problem again after 4.1 is released.

**Comment by BMcKiernan** [comment]
I do have UAC disabled and am having this same problem.

**Comment by MartinBriza** [comment]
@BMcKiernan Does it still crash with 4.1.0 for you, please?
