### ISSUE TITLE
Constantly Crashing in Fedora

### ISSUE THREAD

**Issue by randoogle** [MartinBriza/MediaWriter#64]
I'm running Fedora 24, and wanting to try booting the live ISO before upgrading to 25. Every time I open MediaWriter and select any of the options, it crashes (mostly, it just disappears, but sometimes it crashes so badly that my entire system halts, and no combination of keyboard commands will free it up; I have to physically power it down).

The majority of the time, I can select "Fedora Workstation," and then the information window shows with the "Create Live USB" button in top right. The moment I click on that, though, I get a flash of an interface, and then the window either disappears, or is left blank. Sometimes I can't even get that far, it's pretty random.

**Comment by MartinBriza** [comment]
It's hard to be correct without seeing the actual backtrace but most
likely, this is caused by the buggy nouveau driver (or how Qt uses it).
Unfortunately there's nothing I can do about it for you. :(

2017-01-30 16:46 GMT+01:00 randoogle <notifications@github.com>:

**Comment by MartinBriza** [comment]
Can you please post the backtrace of the crash?

**Comment by randoogle** [comment]
Here's what I've got. I've since moved on and used dd to create the bootable drive.
[media_writer_crash.zip](https://github.com/MartinBriza/MediaWriter/files/873379/media_writer_crash.zip)

**Comment by MartinBriza** [comment]
From what I can see, it's caused by the nouveau driver. You'll have to report this against it either in Fedora or upstream, sorry.
