### ISSUE TITLE
kde-jam in not in FMW labs; last good build was in 20170101.n.0 It was good in f25

### ISSUE THREAD

**Issue by satellitee** [MartinBriza/MediaWriter#65]
last good build was in 20170101.n.0 It was good in f25

**Comment by satellitee** [comment]
4.0.8-0,fc25

**Comment by satellitee** [comment]
users are on #fedora-audio IRC freenode

**Comment by MartinBriza** [comment]
We use only official releases. When there is no supported release of KDE-jam, it will disappear from the list in FMW.
