### ISSUE TITLE
Make alternative Fedora options more visible

### ISSUE THREAD

**Issue by lupinix** [MartinBriza/MediaWriter#66]
Hi,

in our local user group I recommended media writer some time ago and got some feedback now: Most of them did not recognize, that the three vertical dots represent the alternative Fedora options. I did not recognize right now as I'm dd'ing most time. But it is true: If you take a look at the [screenshot](https://raw.githubusercontent.com/MartinBriza/MediaWriter/master/dist/screenshots/linux_main.png) there is no obvious indication, you have to point the mouse over the three dot row to get it.

Therefore I request to change that behaviour by adding an option "Alternative Fedora flavours" at same level as the three other options workstation/server/own instead of the three dots. This improves user experience for peole interested in those alternative versions. I'm also speaking as Fedora Astronomy, KDE and LXQt (new in Fedora 26) maintainer as I'd like to recommend users to use the mediawriter, without having to explain how to use it. 

Compare getfedora.org, we have small "Want more Fedora options?" section there with a small explanation that could be used here too.

Greetings,
Christian

**Comment by MartinBriza** [comment]
Ping @jimmac what do you think about this?

**Comment by jimmac** [comment]
View-more is a pattern that's been rolling out with more and more applications. The more apps will use it, the more familiar it becomes. It didn't pose problems during the user testing of GNOME initial setup. Might be worthwhile to include less common distros in a use test.

Similar choice had to be made with distros as with popular languages. While it sucks if your mother language/distro of choice isn't the first class citizen and is below the fold, the number of items in the list is cognitively limited and promoting fedora spins to the top cut isn't possible, I'm afraid.

**Comment by lupinix** [comment]
Well, we are talking about the **Fedora** mediawriter, so there should an more obvious option for the options and choices Fedora provides. Please recognize: I'm only requesting making the one option for alternative flavours more obvious, I'm not asking to list each spin at first level here. So Workstation and Server are still at higher level than all Spins and Labs.

**Comment by MartinBriza** [comment]
@jimmac A lot of applications do use that pattern... but in GNOME. Meanwhile quite a big percentage users of this tool will see such pattern for their first time because most of the userbase is coming from Windows.

**Comment by jimmac** [comment]
It's a pattern common on mobile platforms where it originates from.

**Comment by lupinix** [comment]
Is there any **serious** reason for not adding that single entry for the alternative options? I mean it is just replacing the three vertical dots with something more obvious… From technical level it is still the same structure, but it improves user experience and IMHO also matches structure of getfedora.org better. getfedora.org even lists all desktops seperately, what I'm not requesting right now.

Please recognize that I'm requesting a rather small change here, that has *nothing* to do with personal preferences. My personal preference would be a full choice of desktops, but as I take account of Fedora.next I'm only requesting that change here to help users to get alternatives (listed on a seperate page, no change here!) if they want. My purpose is to have a self explaining software, due to the comments I got from students I asked to download and create a stick for some class I see that a signifant part of users have problems here. They told me that this is not intuitive. As we had a scientific use case I told them to choose Fedora Scientific. 

Now my personal opinion: This is **Fedora** mediawriter, Fedora is a huge community not only consisting of GNOME. So the alternative options should not be that hidden, also to respect the people doing great work on all these alternatives. I see the point that a complete list of all options at first level makes the mediawriter confusing for new users, but this is not what I'm requesting here anyway. I really don't belive that adding **one** option for alternatives breaks cognition. This can't be true.

**Comment by lupinix** [comment]
Also: We are not a mobile platform like Android, so people expect applications behaving like typical desktop applications (by typical I think about Windows-like behaviour to be honest, that's what most users know)

**Comment by jimmac** [comment]
getfedora.org lists three products to download. Workstation, Server and Atomic. Listing three items is ideal, easy to scan and pick (Generally the cognitive threshold is around 6 items). The design of the imager was aiming at a selection of 4 items. When I was tasked in creating the tool, it was not called Fedora Media Writer and the list of operating systems was not limited to Fedora. Thus the Ubuntu distro in the list[1]. However upon closer inspection, it now only lists the Fedora Workstation and Server these days. It's perfectly fine to add Atomic to the list to mirror the website.

**Comment by lupinix** [comment]
getfedora.org also lists the other desktops (scroll down), under "Want more Fedora options?". Here we even have the icons for the single desktops (what I'm not requesting on first level here, as we would get a large list here).

**Comment by jimmac** [comment]
Scrolling down is the equivalent to expanding the list.

**Comment by lupinix** [comment]
Who defines that equivalence? For me that is not the same.

**Comment by jimmac** [comment]
It's not the same in that the view-more pattern emphasizes the initial choice. It says that the three picks is very likely what you need. only then you are given the choice to drill down among the less likely choices.

**Comment by lupinix** [comment]
Maybe I should implement and show what I mean… I'm talking about feedback I got from users, not theory on design which gives a rough guideline on how a graphical interface should look like to be easy to use.

**Comment by kkofler** [comment]
That "…" is really not discoverable. It took me a while to figure out that it was clickable at all.

And getfedora.org is not a good example to follow, because it goes to great lengths to hide the spins for no good reason:
https://pagure.io/design/issue/411
https://pagure.io/design/issue/412

**Comment by kkofler** [comment]
The biggest issue with the 3 dots is that the area is also used as a status indicator (checking for updates), so it looks like a progress indicator. It is not intuitive at all that the same area is also used as a clickable button.

**Comment by MartinBriza** [comment]
It doesn't anymore, in master. Next version will look like this (if you have a dark desktop theme):

![screenshot from 2017-03-03 10-30-14](https://cloud.githubusercontent.com/assets/3977440/23545629/7396b7a4-fffc-11e6-81c9-b5ae017ad7d0.png)

**Comment by MartinBriza** [comment]
The biggest issue has been solved. For futher discussion about concrete UI elements and bugs, please open new reports where we can continue discussing further changes. However, considering the lack of critique from regular users, I don't think there will be much change to how the separate Fedora flavors are laid out in the main interface.
Closing this report.
