### ISSUE TITLE
Download resulted in 0-byte file and MediaWriter is ok to write it to USB drive

### ISSUE THREAD

**Issue by roman-yepishev** [MartinBriza/MediaWriter#68]
System: WIndows 10 Pro
Release: FedoraMediaWriter-win32-4.0.7

For some reason my Fedora 25 download resulted in 0 byte file in the Downloads folder with the correct image name.

Subsequent restarts of mediawriter would not re-verify the downloaded image and will happily write nothing to the USB drive.

There was no indication of any cached data, so the only way to figure out something broke was to use the custom image selection menu item and notice the empty .iso image.

**Comment by MartinBriza** [comment]
I think this will be alright with the next version, I made some changes to the download code to not only make it more reliable but also to inform the user better in case something goes wrong.
