### ISSUE TITLE
Media Writer takes too long to load

### ISSUE THREAD

**Issue by ekis** [MartinBriza/MediaWriter#69]
Over the course of resolving #21 it was discovered that there are systems on which Media Writer would take an appalling amount of time to load, which effectively led to a misreported hang/freeze of the application.

On an idle Win 7 SP1 system, with 6-core i7-5820k CPU with 32 GB DDR4 and a fast SSD, the it took ~75 seconds to load the application. Tested versions:

- 4.0.7 (at the time of writing, the one available for download from Fedora's site)
- 4.0.8 (at the time of writing, the latest release version from master)
- 4.0.8-g28a695e (an ad-hoc debug release, provided by @MartinBriza)

Provided [here](https://s4.postimg.org/ajebpyne5/Capture.jpg) is a list of Microsoft packages installed on the system that exhibited the slowdown.

**Comment by MartinBriza** [comment]
Thanks for reporting this. I'll test the latest builds on some Win7 machines so I see how it behaves for me. In case it doesn't exhibit this problem for me, we'll see about a different approach to debug this.

**Comment by MartinBriza** [comment]
Hello, please try running this: https://mbriza.fedorapeople.org/FedoraMediaWriter-win32-4.0.8-57-g278efc9-debug.exe . Download will be available in about an hour (upload speeds are pretty bad and it's 375MB large).
It will put a FedoraMediaWriter.log file into your Documents folder. Please upload it here so we can see what is happening under the hood.

**Comment by ekis** [comment]
Did you change anything in this build? Startup is now screaming - less than 3 seconds! :)

```
D@12ms: Application constructed ((null):0)
D@12ms: Injecting QML context properties ((null):0)
D@16ms: WinDriveProvider construction ((null):0)
D@16ms: DriveManager construction ((null):0)
D@16ms: ReleaseManager construction ((null):0)
D@21ms: Loading the QML source code ((null):0)
W@696ms: qrc:/components/DownloadDialog.qml:82:26: QML Item: Binding loop detected for property "width" (qrc:/components/DownloadDialog.qml:82)
D@862ms: Starting the application ((null):0)
D@862ms: WinDriveProvider Looking for the drives for the first time ((null):0)
D@862ms: WinDriveProvider Finished looking at drive letters ((null):0)
D@862ms: WinDriveProvider "\\\\.\\PhysicalDrive0" is present ((null):0)
D@862ms: WinDriveProvider "\\\\.\\PhysicalDrive0" IOCTL_STORAGE_QUERY_PROPERTY ((null):0)
D@862ms: WinDriveProvider "\\\\.\\PhysicalDrive0" IOCTL_STORAGE_QUERY_PROPERTY with a bigger buffer ((null):0)
D@862ms: WinDriveProvider "\\\\.\\PhysicalDrive0" detected: "Samsung" "SSD 850 PRO 256G" , nonremovable notUSB ((null):0)
D@862ms: WinDriveProvider "\\\\.\\PhysicalDrive1" is present ((null):0)
D@862ms: WinDriveProvider "\\\\.\\PhysicalDrive1" IOCTL_STORAGE_QUERY_PROPERTY ((null):0)
D@862ms: WinDriveProvider "\\\\.\\PhysicalDrive1" IOCTL_STORAGE_QUERY_PROPERTY with a bigger buffer ((null):0)
D@862ms: WinDriveProvider "\\\\.\\PhysicalDrive1" detected: "Samsung" "SSD 850 EVO 250G" , nonremovable notUSB ((null):0)
D@862ms: WinDriveProvider "\\\\.\\PhysicalDrive2" is present ((null):0)
D@862ms: WinDriveProvider "\\\\.\\PhysicalDrive2" IOCTL_STORAGE_QUERY_PROPERTY ((null):0)
D@862ms: WinDriveProvider "\\\\.\\PhysicalDrive2" IOCTL_STORAGE_QUERY_PROPERTY with a bigger buffer ((null):0)
D@862ms: WinDriveProvider "\\\\.\\PhysicalDrive2" detected: "Samsung" "SSD 840 PRO Seri" , nonremovable notUSB ((null):0)
D@862ms: WinDriveProvider Finished looking for the drives for the first time ((null):0)
W@864ms: QSslSocket: cannot resolve TLSv1_1_client_method ((null):0)
W@864ms: QSslSocket: cannot resolve TLSv1_2_client_method ((null):0)
W@864ms: QSslSocket: cannot resolve TLSv1_1_server_method ((null):0)
W@864ms: QSslSocket: cannot resolve TLSv1_2_server_method ((null):0)
W@864ms: QSslSocket: cannot resolve SSL_select_next_proto ((null):0)
W@864ms: QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb ((null):0)
W@864ms: QSslSocket: cannot resolve SSL_get0_next_proto_negotiated ((null):0)
W@864ms: QSslSocket: cannot resolve SSL_set_alpn_protos ((null):0)
W@864ms: QSslSocket: cannot resolve SSL_CTX_set_alpn_select_cb ((null):0)
W@864ms: QSslSocket: cannot resolve SSL_get0_alpn_selected ((null):0)
D@2148ms: Download Trying to download from a mirror: QUrl("https://getfedora.org/releases.json") ((null):0)
W@2519ms: QSslSocket: cannot call unresolved function SSL_get0_next_proto_negotiated ((null):0)
D@2724ms: Download Finished successfully ((null):0)

```

**Comment by MartinBriza** [comment]
I didn't change anything related to your problem so I'm even more anxious about this... :) Let's see how well it behaves when there's a final build.

**Comment by MartinBriza** [comment]
Please try downloading this release: https://github.com/MartinBriza/MediaWriter/releases/tag/4.0.95 and check if it still has the problem you reported.
I guess if it's okay, we can close this bug.

**Comment by ekis** [comment]
Just tested on Windows 10 - works like a charm.
I think it is safe to close this issue.
