### ISSUE TITLE
Windows Package signed.

### ISSUE THREAD

**Issue by alh54** [MartinBriza/MediaWriter#74]
Hi,
I have installed FedoraMediaWriter-Win32-4.0.95.exe on Windows 7 x86_64, i could run FMR perfectly.
It's just to say that this package is signed, Here are the informations I got:
This signature is valid
mail: m@rrtinbrize.cz
date: Monday March 20 2017 16:46:57
organization: Symantec Time Stamping Services Signer - G4
Thank you for your efforts.

**Comment by MartinBriza** [comment]
Are you sure about the mail? That doesn't seem like my email address.

**Comment by alh54** [comment]
excuse my mistake, here is the correct:
m@rtinbriza.cz

**Comment by MartinBriza** [comment]
Cool. Thanks for letting me know. I'll close this then. :)
