### ISSUE TITLE
Media Check Fail

### ISSUE THREAD

**Issue by Bazalia** [MartinBriza/MediaWriter#79]
I downloaded FMW from the fedora website and went through the process of creating a live USB. Everything seemed fine and FMW finished writing. But when I try to boot from the USB I get [this](http://imgur.com/6aKgCpg) error.

I have a self built desktop machine running x64 Windows 10 with legacy bios mode. The USB I am using is a SanDisk Ultra with 32GB.

**Comment by MartinBriza** [comment]
The problem you're experiencing (and which will get slightly better with the next FMW version, however it won't be completely gone) lies in the fact Windows writes a System Volume Information folder to every flash drive you connect to it. The most reliable way to avoid this is to pull out the flash drive right after the writing has finished and reinsert it when you have shut down Windows.
I'm going to add a message telling Windows users to do so to be sure the OS didn't mess up their drive. This is definitely a bug, however it's pretty much unsolvable for us.
However, if the media check passed in Fedora Media Writer, you can be sure the flash drive is safe to boot even before media check on bootup, so you can just skip it.

**Comment by poetnerd** [comment]
I experienced this exact same problem today.  My bootable USB drive was created on a Mac. However I was booting on a brand new Windows computer.  At the very least we should document this case, or perhaps provide some kind of pre-boot script that can clean up the mess made.
