### ISSUE TITLE
mediawriter crashing on boot in winjunk 10

### ISSUE THREAD

**Issue by slecrenski** [MartinBriza/MediaWriter#80]
This is not fixed even when using the beta release from #21 

![image](https://cloud.githubusercontent.com/assets/1291050/24651865/6cf8053c-18fd-11e7-85b5-db7f29d1782b.png)

C:\Program Files (x86)\Fedora Media Writer>dumpbin /dependents mediawriter.exe
Microsoft (R) COFF/PE Dumper Version 14.00.23026.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file mediawriter.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    Qt5Core.dll
    Qt5Gui.dll
    Qt5Network.dll
    Qt5Qml.dll
    Qt5Widgets.dll
    dbghelp.dll
    libgcc_s_sjlj-1.dll
    KERNEL32.dll
    msvcrt.dll
    SHELL32.dll
    libstdc++-6.dll
LINK : fatal error LNK1328: missing string table

**Comment by MartinBriza** [comment]
Did you modify your PATH or any other relevant variable? It seems FMW tries to link against a SSL library shipped with some application by Intel instead of the one included in the FMW package.

**Comment by MartinBriza** [comment]
Yes, I'm fairly certain this is the reason the application is crashing for you. Qt prefers ssleay32.dll over libssl-10.dll we ship. If ssleay32.dll is found first, it tries to use that instead. While you probably shouldn't have that library in your PATH, this is a problem we should solve in Fedora.
I have opened a bug here: https://bugzilla.redhat.com/show_bug.cgi?id=1438740

**Comment by slecrenski** [comment]
Please statically compile everything if you can.  Qt and their silly delay loaded annoyingly obfuscated dll dependencies.  Has anyone actually even used the theoretical benefit of dll's?  I think I've maybe once or twice but just for a quick patch.  Except for of course kernel shared object libraries dll's should be avoided like the plague.

I'll modify my path to get it working for now.  Thanks.

On another side note: Why are you guys using Bugzilla instead of GitHub issues?

**Comment by MartinBriza** [comment]
Fedora packages are not hosted on Github. For Windows packages, we use
Fedora MinGW packages to build everything, which brings a few issues, one
of them is this one unfortunately.
This also explains why we're not linking statically - it would require a
lot of manual tweaks. Also mediawriter itself is hosted as a Fedora package
and Fedora packaging guidelines prohibit bundling...


2017-04-04 13:01 GMT+02:00 Stephen Lecrenski <notifications@github.com>:

**Comment by MartinBriza** [comment]
The Fedora package has been patched and the updated package is already available in the testing repositories. Next FMW release should be fine in this regard. Thanks for reporting this non-obvious bug! Please keep in touch if you have any other problem or suggestion.
