### ISSUE TITLE
broken start menu item on Windows 7 Enterprise x64 with 4.1.0 prerelease

### ISSUE THREAD

**Issue by realsobek** [MartinBriza/MediaWriter#81]
I installed FedoraMediaWriter-win32-4.0.95.exe on Windows 7 Enterprise 64 bit in order to put Fedora 26 Alpha on a USB thumb drive. It works great :)
The EXE file is digitally signed. Your name appears in 'Digital Signatures' tab.

I noticed 2 problems with the start menu item on the same computer with the same operating system. I guess both are related to the installer.
Problem 1: wrong path to icon file
It tries to load the icon from:
`%programfiles%\Fedora Media Writer\logo.ico`
This file is not present. The folder (at least on Windows 7 64 bit; for 32 it is fine) and the file name is wrong. This path must be used:
`%programfiles(x86)%\Fedora Media Writer\mediawriter.ico`

Problem 2: wrong path to EXE file
The path used by default is:
`%programfiles(x86)%\Fedora Media Writer\app.exe`
This file is not present. This path must be used:
`%programfiles(x86)%\Fedora Media Writer\mediawriter.exe`

**Comment by MartinBriza** [comment]
Oh, thank you very much for noticing! I'll fix this right away.

**Comment by MartinBriza** [comment]
There, fixed. It should be okay in the following release. I think the 32b and 64b paths should be handled automatically.

**Comment by realsobek** [comment]
thanks, awesome :)
