### ISSUE TITLE
signing algorithm of 4.1.0 prerelease

### ISSUE THREAD

**Issue by realsobek** [MartinBriza/MediaWriter#82]
On Windows 7 for the file FedoraMediaWriter-win32-4.0.95.exe in the properties window in 'Digital Signatures' tab the signing algorithm is "sha1".
I read that this algorithm is considered broken.
Is it possible to update to sha256 or later?

**Comment by MartinBriza** [comment]
Good point. I'll check the possibilities with the current signing infrastructure.

**Comment by MartinBriza** [comment]
I'll just leave this here for future reference:
https://sourceforge.net/projects/osslsigncode/files/osslsigncode/

**Comment by TruboXL** [comment]
Possibly an one shot bug by Windows, after choosing "Run anyway", it won't appear again...
Windows 10 Pro Creators Update
![risk](https://cloud.githubusercontent.com/assets/12658589/26252706/9424d130-3ce3-11e7-8f67-89dd235ee761.PNG)

**Comment by MartinBriza** [comment]
Yeah, SmartScreen being smart. If the table afterwards is blue and not yellow, it's fine. I've got a new certificate and it's not yet registered by Microsoft's "smart" systems as secure.
