### ISSUE TITLE
Working but with some error

### ISSUE THREAD

**Issue by Adrianzo** [MartinBriza/MediaWriter#83]
I get this message inline after the check passed:

> It is OK to use this media.
> /bin/livecd-iso-to-disk: line 492: : command not found
>
>    WARNING: This will DESTROY ALL DATA on: /dev/sdb !!

then the process seems to continue with no problems. Haven't tried booting the usb key yet, though...

**Comment by MartinBriza** [comment]
You get this error when? What tool are you using? Which version? In which OS? This doesn't seem like a Fedora Media Writer error...

**Comment by Adrianzo** [comment]
I'm using Fedora 25 and livecd-tools 24.2... I was running:

$ sudo livecd-iso-to-disk --reset-mbr --format --crypted-home --home-size-mb 6000 Fedora-Security-Live-i386-25-1.3.iso /dev/sdb

Got the aforementioned error message but the proccess completed with no problem.

Maybe I should report as a bug to fedora?

**Comment by MartinBriza** [comment]
This project is packaged as mediawriter in Fedora. I guess opening a Red Hat Bugzilla bug or maybe finding a tracker for livecd-iso-to-disk upstream would work for you, sorry.
