### ISSUE TITLE
Media Writer Fails to write any image to an SD Card on Fedora 26

### ISSUE THREAD

**Issue by aruiz** [MartinBriza/MediaWriter#84]
Every time I try to write an ARMv7 image (either by downloading or selecting them from the file chooser) I get this error/notification:

![screenshot from 2017-04-19 17-50-12](https://cloud.githubusercontent.com/assets/2845/25191808/adc9451c-2528-11e7-9b1b-28cdf4628c82.png)

**Comment by MartinBriza** [comment]
Hey,
thanks for the report. I've got a similar one during the test day last week: https://bugzilla.redhat.com/show_bug.cgi?id=1443981 .
I'll see about fixing that this week.

**Comment by MartinBriza** [comment]
So this seems to be caused either by udisks or selinux. Closing here, for further progress please watch the bug I mentioned in the previous comment.
