### ISSUE TITLE
it's not working on windows 7

### ISSUE THREAD

**Issue by Moullablad** [MartinBriza/MediaWriter#87]
Hello i tried install your version of media writer but it dosen't work i have winodws 7 pro 64bit.

**Comment by MartinBriza** [comment]
You'll have to be a bit more specific than that, sorry.
First, please specify which version of Fedora Media Writer you used. When did it fail? When you tried to install it or when you tried to start it?
What graphics hardware do you have? Do you have the latest available driver?

**Comment by rugk** [comment]
Complementing https://github.com/MartinBriza/MediaWriter/issues/90, I seemed to be welcomed by a horrible UX here. Not blaming you, just seems to be doomed… :wink: 

So, basically it does not start. I cannot see it in the task manager (or, when I'm lucky, only a short amount of time).

Windows 7, x64

**Comment by MartinBriza** [comment]
@rugk Which version did you try? If anything below 4.1.0, please get that from the Releases section on this GitHub page. It's a lot more stable.

In case if that doesn't help, please specify which graphics hardware and driver are you running on and if there are any special settings done to your system, especially regarding user permissions.

**Comment by rugk** [comment]
I used the one from getfedora.org.

**Comment by MartinBriza** [comment]
Have you tried the one from the Releases section here then?

**Comment by rugk** [comment]
Yeah, the latest version (4.1.0) works. (It only says that a "new version" v4.0.8 is available, …)

**Comment by MartinBriza** [comment]
So it should be alright then. :) If not, just reopen the issue and we'll see what can be done.
