### ISSUE TITLE
Window flickering on Fedora 22

### ISSUE THREAD

**Issue by drizt** [MartinBriza/MediaWriter#88]
Left part of MediaWriter window is flickering. See screenshot http://storage7.static.itmages.com/i/17/0602/h_1496384213_3834085_56cccdee0d.png

**Comment by MartinBriza** [comment]
Fedora 22 is not supported for more than a year. Please upgrade to at least Fedora 24 (which will get obsoleted in about two months) and check if the issue is fixed.
