### ISSUE TITLE
Freezes when starting download

### ISSUE THREAD

**Issue by rugk** [MartinBriza/MediaWriter#90]
When a download is started, the whole system freezes.
It does not matter whether there is already an USB plugged in or not. It fails immediately after the "Create Live USB" button is pressed. Reproducible.

Fedora 25, Wayland

**Comment by squimrel** [comment]
It would be great if you could add the `FedoraMediaWriter.log` to this issue? It's most likely in your documents folder or whatever you set `XDG_DOCUMENTS_DIR` to.

**Comment by rugk** [comment]
That's too much, "most-likely". :wink: 
No, there is no such file… Maybe it did not even came that far as to write that file?

**Comment by MartinBriza** [comment]
So first things first: are you running on a nvidia graphics card with the nouveau driver?

**Comment by rugk** [comment]
nouveau

**Comment by MartinBriza** [comment]
Then I'm sorry but there's nothing I can do about this. Qt apps crashing with nouveau a longstanding problem with the driver which nobody seems to really care about... :/

**Comment by MartinBriza** [comment]
You can of course try poking the nouveau guys, either on the fedora bugzilla or the freedesktop one...

**Comment by rugk** [comment]
Actually I've never seen another program crashing with that strange reason… Maybe this quite essential program . Also it is very strange that it actually freezes (it does not crash, BTW!) in the most important moment.

Anyway, give us some bug reports or so, where we can complain.

**Comment by MartinBriza** [comment]
The complete list would be here:
https://bugzilla.redhat.com/buglist.cgi?quicksearch=component%3Axorg-x11-drv-nouveau

And there's a bunch of mediawriter-related reports:
https://bugzilla.redhat.com/show_bug.cgi?id=1411172
https://bugzilla.redhat.com/show_bug.cgi?id=1414062
https://bugzilla.redhat.com/show_bug.cgi?id=1443555
https://bugzilla.redhat.com/show_bug.cgi?id=1436839
https://bugzilla.redhat.com/show_bug.cgi?id=1434330
https://bugzilla.redhat.com/show_bug.cgi?id=1426218
https://bugzilla.redhat.com/show_bug.cgi?id=1417432
https://bugzilla.redhat.com/show_bug.cgi?id=1398936

I don't track the upstream bugzilla that often though.

And while it freezes for you, it would probably crash in a while anyway.
Still, a driver problem... :/

2017-06-06 13:07 GMT+02:00 rugk <notifications@github.com>:

**Comment by rugk** [comment]
3 bugs were access-restricted, but everywhere else, I've commented.
