### ISSUE TITLE
Fuzzy flickering font on Win7

### ISSUE THREAD

**Issue by woderkant** [MartinBriza/MediaWriter#97]
Fedora Media Writer win32 4.1.0 (from https://getfedora.org/fmw/FedoraMediaWriter-win32-4.1.0.exe) shows **fuzzy flickering font** on Windows 7 x64 and is hardly readable. Both with and without administrator privileges.

![fedora media writer fuzzy font](https://user-images.githubusercontent.com/30175239/28209883-e8bd7a30-6894-11e7-9746-8561fae7362c.png)

**Comment by MartinBriza** [comment]
Wow, this is a new one. Is there anything special about your install? Did you for example upgrade from a previous Windows editions? What is your graphics hardware and driver, please?

**Comment by woderkant** [comment]
Haven't seen such a behavior before, esp. not on this install. OS is Win7 Pro x64 SP1, nothing special. Graphics adapter is a 2009 `Intel GM45` aka `GMA 4500M HD`. Device Manager shows `Mobile Intel(R) 4 Series Express Chipset Family` with driver provider Intel, date 10/04/2012 and version 8.15.10.2869. Internal and external display – same behavior.
BTW there is no `FedoraMediaWriter.log` created, on Windows, right?

**Comment by MartinBriza** [comment]
I will switch the Windows FMW builds to use the software renderer instead of hardware acceleration and we'll see if it fixes this.

**Comment by MartinBriza** [comment]
Should be fixed by 8f6c16d1adbcf15c4319953259e76d7e70c85951
