### ISSUE TITLE
Version number displayed as a macro in Windows 7 Programs and Features

### ISSUE THREAD

**Issue by anohren** [MartinBriza/MediaWriter#99]
In the list of installed programs in the control panel the media writer lists its version like this:

![capture](https://user-images.githubusercontent.com/3519879/28239648-7b4dcb20-6971-11e7-8904-db2e141d1539.PNG)

**Comment by MartinBriza** [comment]
Oh, yeah, I forgot to actually fill those variables. Thanks for reminding me.

**Comment by truboxl** [comment]
![image](https://user-images.githubusercontent.com/12658589/35495924-883f4826-04fe-11e8-9d18-57351eecd977.png)

Still not fixed in 4.1.1...
